### ISSUE TITLE
[minor] Fireproof versions of Minecraft trees don't produce fireproof logs

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#1028]
It is for the record because there may be technical drawbacks and few benefits into registering fireproof variants of Minecraft woods:

![2015-12-31_14 43 05](https://cloud.githubusercontent.com/assets/1111474/12064855/7909790e-afcd-11e5-9c52-c6492a72fc24.png)

**Comment by Blue64** [comment]
Thanks for the heads up! Saved me some frustration and tinkering. I'd have come across this bug within a month. Gany's Surface makes my vanilla fences no longer fireproof (on purpose of course), and infusing the Fireproof aspect into Vanilla Trees should produce Fireproof Logs (it's sort of expected). I vote for adding the Fireproof Vanilla Variants, because maybe I want a Fireproof Oak Tree that produces Cocoa that I can grow in the Nether, you never know! `:P`
