### ISSUE TITLE
Add IItemHandler capability to all things with inventory

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/ForestryMC#1106]

**Comment by CovertJaguar** [comment]
Assuming you mean when right-clicking with a Backpack on a machine.

It should be fairly straight-forward. Just subclass [InventoryManipulator](https://github.com/ForestryMC/ForestryMC/blob/mc-1.8.9/src/main/java/forestry/core/inventory/manipulators/InventoryManipulator.java) and point InventoryManipulator.get(IInventory) at the new subclass when IItemHandler is detected.

You'll probably need to do the same for [InventoryIterator](https://github.com/ForestryMC/ForestryMC/blob/mc-1.8.9/src/main/java/forestry/core/inventory/wrappers/InventoryIterator.java).

This should provide support for all things in Forestry that interface with Inventories.

I'll get around to this in Railcraft eventually (which uses the same code).

**Comment by CovertJaguar** [comment]
Hmm...having just looked at InventoryUtil...it might be much, much more complex than that since there are a lot of functions that should really be backed by InventoryManipulator or InventoryIterator in there but which aren't. You'll need to fix those functions too, preferably by pointing them at InventoryManipulator or InventoryIterator.

See [InvTools](https://github.com/CovertJaguar/Railcraft/blob/update-1.8.9/src/main/java/mods/railcraft/common/util/inventory/InvTools.java) in Railcraft for examples. Feel free to take anything you can use.

**Comment by CovertJaguar** [comment]
I posted more info in #1091, but I went ahead and added the support to Railcraft. Take what you need.

**Comment by mezz** [comment]
Thanks Covert!
