### ISSUE TITLE
Issue crafting items from agricraft

### ISSUE THREAD

**Issue by BernardoCBranco** [ForestryMC/ForestryMC#1127]
I'm having an issue where I can't craft anything from agricraft with some of the wood types that forestry adds. The wood types that gave me problems were Palm and Zebrawood but there might be more.

**Comment by mezz** [comment]
Thanks for the report!
Sorry, I made a design mistake in Forestry 4 that makes the wood items incompatible with most other mods' expectations.
This has been fixed in Forestry 5, which is aiming to be released for Minecraft 1.9+. Unfortunately it will not be fixed in Forestry 4 because it requires more world-breaking changes.
