### ISSUE TITLE
[Crash 1.8.9] java.lang.AbstractMethodError: forestry.apiculture.tiles.TileHive.getWorld()Lnet/minecraft/world/World;

### ISSUE THREAD

**Issue by miuirussia** [ForestryMC/ForestryMC#1153]
Full log:
http://pastebin.com/PFgBKkFW

**Comment by mezz** [comment]
Thanks for the 1.8.9 report!
I think `getWorld()` is getting messed up by the Minecraft obfuscation, and we need to change the name to make it work.

**Comment by CovertJaguar** [comment]
Yeah, it looks like [IBeeHousing.getWorld()](https://github.com/ForestryMC/ForestryMC/blob/mc-1.8.9/src/main/java/forestry/api/apiculture/IBeeHousing.java#L47) isn't being obfuscated, but TileEntity.getWorld() is obfuscated. Resulting logically in an AbstractMethodError because then TileHive doesn't implement getWorld().

**Comment by miuirussia** [comment]
Will this be fixed in the near future? Or wait for mods update to 1.9?

**Comment by mezz** [comment]
We are going straight for 1.9. This will be fixed before it's released.

**Comment by mezz** [comment]
Related to https://github.com/md-5/SpecialSource/issues/12

I'll be fixing this now, it affects a whole bunch of stuff.
