### ISSUE TITLE
Forestry Wood doesn't work with TC equal trade

### ISSUE THREAD

**Issue by implayin** [ForestryMC/ForestryMC#1225]
I noticed this after updating to Forestry 4 converted all the planks to Larch and then fixing everything up.

Forestry Wood Planks don't work with any block-replacing tools, such as the TC wand focus of equal trade. When shift-right-clicking the planks with the wand focus, it doesn't set the wand to the specific block.

Not sure if this is bug on the Forestry side, or maybe it's just blacklisted somehow?

**Comment by mezz** [comment]
Thanks for the report!
Sorry, I made a design mistake in Forestry 4 that makes the wood items incompatible with most other mods' expectations.
This has been fixed in Forestry 5, which is aiming to be released for Minecraft 1.9+. Unfortunately it will not be fixed in Forestry 4 because it requires more world-breaking changes.
