### ISSUE TITLE
(1.9.4) Forestry Tin and Copper not in the OreDict

### ISSUE THREAD

**Issue by drewbit** [ForestryMC/ForestryMC#1258]
Not sure what else to say, Tin and Copper from Forestry isn't in the OreDict and can't be used by anything.

Forestry Version: forestry_1.9.4-5.0.0.100
Forge Version: forge 1.9.4-12.17.0.1935-1.9.4

**Comment by mezz** [comment]
I am experimenting by having other mods' Copper and Tin take priority. If Forestry detects another mod with Copper and Tin, it will use those and will avoid using its own Tin and Copper in recipes.  This way, when you're mining and crafting you will not get Forestry variants along with others, it will be more unified. I hope to convince other modders to do this too so that only one type is chosen for all mods.

When this happens, I do not register the Forestry items in the Ore Dictionary so that they don't show up in recipes, since they can't be crafted or obtained at all. Should I make recipes to convert from the Forestry item to whatever one is taking priority? Let me know what you think.

**Comment by CovertJaguar** [comment]
Honestly, the Ore Dictionary probably needs some more user friendly utility functions before that will happen. The existing functions are awkward to use at best, downright painful at worst.

**Comment by mezz** [comment]
I should probably create a new registry for this, if we want it to be simple then OreDictionary is a lost cause in my opinion.

**Comment by mezz** [comment]
I'm going to revert this change and look into a more solid solution.
