### ISSUE TITLE
Increase peat energy values compared to charcoal

### ISSUE THREAD

**Issue by estebes** [ForestryMC/ForestryMC#1269]
Buffing maturation speed, burn value or peat engines or maybe even replacing the need for mulch in the carpenter recipe so it doesnt depend on other stuff.

**Comment by SandGrainOne** [comment]
"other stuff" is good. We should try to keep crafting steps in a game about automation.

**Comment by mezz** [comment]
Mulch is fine as-is, but peat could use a buff vs charcoal.

**Comment by Cat09** [comment]
these are some numbers I found searching around: (GigaJoules and Meter^3(a minecraft block))

anthracite coal   : 800-929 kg/m3  26-33 MJ/kg  20.8GJ/m3 - 30.6GJ/m3
Bituminous coal : 673-913 kg/m3  24-35 MJ/kg  16.2GJ/m3 - 31.9GJ/m3
Lignite coal        : 641-865 kg/m3  10-20 MJ/kg  6.4 GJ/m3 - 17.3GJ/m3
Peat moss :                15-17 GJ/kg  
this document has some different numbers
http://www.fao.org/docrep/x5872e/x5872e0b.htm
'Table 36' specifically has some good info, putting compressed dried peat moss at 12GJ/m3

according to that table, a block of peat would have a burn time of about 480 ticks to a coal blocks 800 ticks if it was made from 'crushed coal' or 384(!) compared to if it was anthracite coal.
we could use the reasoning that since coal in minecraft is so common, it is lignite coal - putting it in roughly the same range as the compressed dried peat moss. that would incedentally argue for a mod that adds bituminous and anthracite in rarer deposits.

**Comment by SynfulChaot** [comment]
With how trivial it is to get charcoal vs the automation required for peat, I'd argue that gameplay should trump realism here.  Why else would someone desire to farm peat when they could just make a tree farm?

**Comment by mezz** [comment]
Charcoal:
BuildCraft Stirling Engine for 16000 RF at 10 RF/t

In order to buff peat, I think I will make it burn much faster (more rf/t) than charcoal and increase the quantity dropped. It will have less RF per piece than charcoal.
