### ISSUE TITLE
No tree grows Sipiri

### ISSUE THREAD

**Issue by Interfectivus** [ForestryMC/ForestryMC#1304]
Good afternoon!

I can not get a tree to grow Sipiri! Soot in different tropical biomes and used bone meal, but do not want it to grow ...

Forestry 4.2.12
forge-1.7.10-10.13.4.1614

Please, help...

**Comment by RyanP1991** [comment]
So I poked around for any information about this and found this:
"Apparently trees listed as Tropical for growth climate require "Hot" biomes. Jungle biomes and associated variants are listed as "Warm." Since Sipiri trees also need "Damp" biomes, only Bamboo Forest, Blessed Bog, Majestic Meadow, Rainforest, Tropics, and Wondrous Woods will work for growing Sipiri Trees under normal circumstances (Forestry 3.6.2.19 on Aug. 6, 2015).

**Comment by Interfectivus** [comment]
Hmm ... I do not have these biomes ...

Here is a list of biomes that I have:

Roofed Forest M
Ice Plains Forest M
Ocean
DesertHills
Savanna M
JungleEdge
Flower Forest
Sky
Birch Forest M
MushroomlslandShore
Mega Taiga
Mesa Plateau F
Desert M
River
Ice Mountains
Cold Taiga
Savanna Plateau
Taiga
JungleHills

JungleEdge M
Birch Forest Hills
Extreme Hiils +
Ocean Oil Field
Extreme Hills
Extreme Hills Edge
Mesa Plateau F M
Jungle M
Cold Beach
Cold Taiga M
Plains
ForestHilis
Savanna Plateau M
Deep Ocean
Taiga M
FrozenOcean
Birch Forest Hills M
Mega Taiga Hills
Beach

Extreme Hills + M
Mesa Plateau
Extreme Hills M
Hell
Mushroomlsland
Cold Taiga Hiiis
Mega Spruce Taiga
Mesa
Sunflower Plains
Swampland
Ice Plains
roofed Forest
Savanna
Desert Oil Field
Forest
Jungle
Mesa Plateau M
Birch Forest
Desert

TaigaHills
Mesa (Bryce)
Stone Beach
Swampland M
FrozenRiver

Which of these biomes can I grow Sipiri?

**Comment by mezz** [comment]
I will remove this restriction in Forestry 5, it's confusing.

**Comment by mezz** [comment]
Fixed by this commit in Minecraft 1.10, trees no longer have environment restrictions for growth.
https://github.com/ForestryMC/ForestryMC/commit/4cb1ee4cb1766cc5a30d3961e60818dda3938a74
