### ISSUE TITLE
(1.9.4) Liquid pipes

### ISSUE THREAD

**Issue by Majestyc2k1** [ForestryMC/ForestryMC#1308]
Liquid pipes aren't connecting to the Carpenter. I tried both Ender IO and Power Advantage. Is this intended?

**Comment by mezz** [comment]
About 4 days ago, a new Fluid capability was added to Forge that's written by me and RWTema. It's intended to replace all the old fluid handling and make things compatible and easy to use, once and for all. 

Since I was testing with it, I already moved Forestry over to this new system and it'll be a little while before anyone else supports it. You can [subscribe to the EnderIO issue here](https://github.com/SleepyTrousers/EnderIO/issues/3375).

Forestry version 5.0.6 and earlier should work with any liquid pipes.
