### ISSUE TITLE
[1.7.10] EnderIO facade rendering

### ISSUE THREAD

**Issue by Messorix** [ForestryMC/ForestryMC#1338]
EnderIO facades made with Forestry-type planks do not render properly (as seen below with my cherry wood planks)
The EnderIO devs think it is a bug caused by Forestry rather than EnderIO so...

![2016-07-03_02 12 05](https://cloud.githubusercontent.com/assets/1729627/16543331/7b587d52-40cf-11e6-961a-c9b0177b124b.png)

**Comment by mezz** [comment]
Thanks for the report!
Sorry, I made a design mistake in Forestry 4 that makes the wood items incompatible with most other mods' expectations.
This has been fixed in Forestry 5, which is in alpha right now. Unfortunately it will not be fixed in Forestry 4 because it requires more world-breaking changes.
