### ISSUE TITLE
Crating is documented as not requiring crates

### ISSUE THREAD

**Issue by billgus** [ForestryMC/ForestryMC#1376]
https://forestryforminecraft.info/crafting:carpenterrecipes

The Crating recipe only requires 9 of an item to produce a crated item.  It really needs some crates in the top holder.

**Comment by billgus** [comment]
I found a more accurate picture at
http://feed-the-beast.wikia.com/wiki/Crate

**Comment by danielrossyamitrano** [comment]
It should be noted that the feed the beast wiki uses a very old version of forestry (among other mods). It's documentation it's not updated for that reason.

On the other hand, the official wiki documentation lacks the recipes of many blocks and items, not only the crated ones.

**Comment by mezz** [comment]
Thanks for the report!
@Hanfox or @Nirek-K can you fix this small wiki issue? I took a quick look but got lost in the recipe syntax.

**Comment by HanPrower** [comment]
I have fixed the recipe.

The wiki needs some intense loving anyway. I've had no time since the original setup due to other projects (and no one else seems willing to really do anything with it - not even just devs (who know the most!) dumping information).

I know this isn't really the place, but is there any reason people don't update the wiki? Do people just not want to sign up? The last time the wiki was anonymous it was littered with spam... I could maybe Google reCAPTCHA the edits? Just be nice if people helped update it instead of just stating it's missing stuff ;)

**Comment by CovertJaguar** [comment]
@HanFox About ever couple months someone adds a paragraph or two the Railcraft wiki, but that's about it. Seems only the big modpack wiki's get any love.
