### ISSUE TITLE
Multifarm does not trigger some mod added plant drops

### ISSUE THREAD

**Issue by EnderiumSmith** [ForestryMC/ForestryMC#1386]
Crops harvested by the multifarm do not drop some mod added drops like verdant sprigs from roots.

**Comment by mezz** [comment]
Thanks for the report!
@elucent would fixing this break your mod's balance, or is it ok?

**Comment by elucent** [comment]
It wouldn't break anything, though you don't have to, I'm going to be making all the drops require player interaction come Roots v0.200.

**Comment by EnderiumSmith** [comment]
@elucent So no drops from villagers? Wouldn't that make the mod inaccessible to the ones using autofarms?

**Comment by elucent** [comment]
The Forestry issue tracker might not be the best place for such a conversation, but I don't want gathering those materials to be something you can easily automate.

I have four main reasons for this:

1) It keeps itself in conceptual symmetry with the rest of the mod. The only things in the mod you can automate the production of currently are the rare crop drops or berries, and berries are being phased out next version. I want to make it so that if you want to advance in the mod, you have to do so yourself, in-person, not relying on any machines. I think it fits a little more in the natural theme.

2) Much less clutter for people who don't want to play the mod. With no berries and no automated collection of these items, you won't end up needing to add item voiding onto your tree farms, or build storage space for these limited-use items.

3) It keeps them rare. While I don't want to make these _too_ rare, having to gather them yourself means you can't just accumulate stacks of them passively while your auto-farm runs.

4) It makes space for a few additional features that can improve the drop rate of these items. It's not a big enough mechanic for there to be any complex system there, but maybe getting higher drop rates as you progress through the mod would be a good motivating mechanic. I don't know, haven't tried it yet.

**Comment by Nedelosk** [comment]
Is this still a thing or can I close this ?

**Comment by EnderiumSmith** [comment]
well roots updated to require manual harvesting(breaking the block) so i guess its obsolete.
