### ISSUE TITLE
Some bugs and improvements to wild bee hives

### ISSUE THREAD

**Issue by EnderiumSmith** [ForestryMC/ForestryMC#1391]
1-wild bee hives should apply the bee effect to entitys hit.

2-marshy hives spawn in jungles. The climate matches but it might bee a good idea to blacklist vanilla jungles to marshy hives. A config for biome blacklisting for specific bee hives would be great.

3-the enderdragon can destroy end hives.

4-wild end bees should not attack endermen if not angry.

5-end hives still use 1.7 rarity but the end is infinite now. Limiting hives to the dragon lair would be the best approach as to keep them rare and they need the dragon egg as flower so it makes sense.

**Comment by SandGrainOne** [comment]
Maybe introduce chorus fruit as flower for the End species branch? Using the dragon egg as flower and having the bees themselves too rare is causing issues on larger servers.

**Comment by EnderiumSmith** [comment]
You can get end drones from end towers/villagers. Its easy to breed out end flower.

**Comment by Nirek-K** [comment]
I intended to add the chorus thing to the end flower but haven't gotten around to it, and villagers now can have end drones as an expensive trade (and mundane species, for servers/players with bad luck with biomes)

**Comment by mezz** [comment]
1. Tropical bees can already kill you very quickly if they poison you, I don't want to raise the rate.
2. Blacklisting certain biomes makes sense.
3. Hives being destroyed by the dragon is fine because there are plenty in the end islands.
4. That's valid, the end bees and endermen should get along.
5. I don't think the end bees should be that rare, all it does is encourage players to hoard them and prevents everyone from getting them. Using the chorus as a flower would help this too. I should probably lower the spawn rate a bit though, they're really all over the end right now.

Can you break this into new issues for 2 and 4, and close this one?
