### ISSUE TITLE
[API-TreeManager] TreeManager doesn't work properly

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#1429]
crash-log: http://hastebin.com/oyemutacew.m
example/test mod: http://hastebin.com/efovivusuj.java
forestry: 1.10.2-5.2.9.241 and 1.10.2-5.2.10.248

**Comment by mezz** [comment]
I've been looking at this a while and here's what I understand so far:
The sapling block has a `SaplingStateMapper`, which needs to be registered in PreInit, if I register it later then it doesn't work.
Your sapling needs to be defined before the mapper can be properly registered, but there is no way to do that before Forestry's PreInit since the API isn't set up yet.

I think I'll have to either come up with a different API or have addons register their own sapling blocks.

**Comment by Nedelosk** [comment]
I think the best way is a event that we call up before we register the sapling block.

**Comment by mezz** [comment]
That makes sense.

**Comment by Nedelosk** [comment]
I think it work now, @marcin212 can you test it please ?

**Comment by marcin212** [comment]
In order to catch the AlleleSpeciesRegisterEvent for ITreeRoot, You'd need to be registered in the EventBus in FMLConstructionEvent. Other than that, everything seems to work fine. 

https://img.bymarcin.com/screenshot-2016-09-18_19-04-35.png
