### ISSUE TITLE
Multifarm not replating saplings. 1.10.2

### ISSUE THREAD

**Issue by Landriss** [ForestryMC/ForestryMC#1485]
I have noticed that the saplings will not replant themselves if none remain in the input box. All saplings are moved to the lower output boxes and the Arboretum Portions of the farm just stop working unless I manually add more saplings to the upper right box.

Last two tests included 2 circuit board with two for crops, leaving 2 for the arboretum and last test was 4 slot circuit board with 2 for crop and 2 for arboretum.

**Comment by MauveCloud** [comment]
I reported the same issue several days ago:
https://github.com/ForestryMC/ForestryMC/issues/1461
but I was told it is now intentional for it to do that.

If you want the saplings to go back in automatically, there are things from other mods that can help with that, such as a transfer node, item filter, and pipe from Extra Utilities 2, a grated hopper and ducts from the Hopper Ducts mod, item conduits from Ender IO, or import and export buses from Applied Energistics 2 (all of which have builds available for Minecraft 1.10.2, though some might be in early alpha or beta)

**Comment by mezz** [comment]
Yes, this is a change of behavior in order to give players more control over the farm.
