### ISSUE TITLE
[1.11.2] Broken Crafting Recipes

### ISSUE THREAD

**Issue by DarkRabe** [ForestryMC/ForestryMC#1559]
на Форестри последней версии нет многих крафтов: оловянной банки, всех видов шестеренок, а также прочного корпуса и т.д. JEI показывает, что рецепт есть, но при выкладывании рецепта на верстаке, конечный продукт отсутствует. Исправьте баг или подскажите как исправить, если причина не в моде а у меня.

### Google Translated Text:
Forestry on the latest version lacks many of the craft: tin cans, all kinds of gears, as well as the hull, etc. JEI shows that there is a recipe, but the recipe vykladyvanii on the bench, the end product is missing. Correct the bug, or tell me how to fix it, if the cause is not in vogue and I have.

**Comment by DarkRabe** [comment]
Вы бы хоть написали что с этим делать...

**Comment by Nedelosk** [comment]
Please write english. Not everyone can speak or read russian.

**Comment by Nedelosk** [comment]
Google Translated Text:
Forestry on the latest version lacks many of the craft: tin cans, all kinds of gears, as well as the hull, etc. JEI shows that there is a recipe, but the recipe vykladyvanii on the bench, the end product is missing. Correct the bug, or tell me how to fix it, if the cause is not in vogue and I have.

**Comment by Nedelosk** [comment]
Thanks for the report!
It is fixed in the last version of forestry .
