### ISSUE TITLE
[1.11.2]Oredict carpenter problem

### ISSUE THREAD

**Issue by Myknakryu** [ForestryMC/ForestryMC#1568]
Minecraft version: 1.11.2
Forge version: 2216
Forestry version: 5.3.0.26

Putting other wood than saved in template in carpenter, starts processing items but when crafting is nearly finished game freezes and crashes.

Crash logs:
https://gist.github.com/Myknakryu/9920d4ddd5461e6fc2abc62855943ce4

Video:
https://youtu.be/HhN0y3puyUA

**Comment by Bienebia** [comment]
Hello,

i get the excat same error. I had an old recipe in the carpenter and put wood inside and took it out again, because i saw it was the wrong recipe. I changed the recipe and put the wood in again and than it startet to work, but than it crashed. And now i can't open the world again.

Minecraft version:1.11.2
Forge version: 13.20.0.2216
Forestry version:5.3.0.26
also tryed version 5.3.0.28

**Comment by DingoX3** [comment]
I have a similar issue. I had oak wood in the recipe making wood pulp. I shift clicked a stack of birch wood in there and the server crashed. Playing on modpack: One Elf Squared --->[Curse profile](https://mods.curse.com/modpacks/minecraft/256325-one-elf-squared)

Full crash log here: https://paste.fedoraproject.org/541377/84967814/

Minecraft version: 1.11.2
Forge Version: 13.20.0.2226
Forestry Version: 1.11.2-5.3.0.30
