### ISSUE TITLE
Multifarm not replanting seeds

### ISSUE THREAD

**Issue by Zetharion** [ForestryMC/ForestryMC#1576]
Playing All The Mods Expert pack and I have the smallest multifarm set to an Automatic crop farm using an intricate circuit with bronze tubes.  I put the wheat seeds in manually and it will plant them.  Once the wheat matures and is harvested any seeds that drop are placed in the output slots instead of refilling the six seed slots on the right like it used to.  Is this an intended mechanic now?

Testing using modpack version 1.0.22 that is using the .360 version of Forestry.

**Comment by Nirek-K** [comment]
In 1.10+ the farm does not 'automatically' anything into the sapling slot, and is intended, yes.

**Comment by Zetharion** [comment]
Thanks for the quick response, guess I will have to re-route the seeds back in then.

**Comment by MauveCloud** [comment]
I reported a similar issue a few months ago (with saplings, rather than seeds, so I'm not sure it counts as a duplicate): #1461

I was told Forestry "does not stand alone very well".  You're already using it in a modpack.  I haven't looked at that one myself, but I'd be _very_ surprised if a pack calling itself "All The Mods" doesn't include some sort of piping system.

**Comment by Zetharion** [comment]
Oh it does, its just that of all the years I have been using Forestry I haven't had to do that, but good to know that I will have to moving forward, which is fine.
