### ISSUE TITLE
Wood Blocks are invisible

### ISSUE THREAD

**Issue by Nitrama** [ForestryMC/ForestryMC#1612]
For issues:
I have no idea why:

Minecraft:1.11.2
Forge:13.20.0.2252
Forestry:1.11.2-5.3.2.50

**Comment by LuigiHutch** [comment]
No screenshots? No log? No modlist?

**Comment by Nedelosk** [comment]
Thanks for the report!
Do you have BetterFoliage installed ? There is a bug with that mod. https://github.com/octarine-noise/BetterFoliage/issues/117

**Comment by Endmateria** [comment]
Are your log texture names standardized?  Sorry, I don't know code... I was just digging into the texture differences between your mod and other tree mods.  Vanilla and BOP trees use "log" and "log top" for the tree texture names.  Yours uses "bark" and "heart".  Could it be that he uses an algorithm that just looks for "log textures", hence it doesn't recognize your unique texture names and consequently doesn't know what to do with them?  I only ask cuz if this is indeed the case, then it might be easier in the long run to standardize your file/texture names rather than having all the other mod authors adapt to your setup.  Could save you from a lot of redundant mod conflicts down the line.  Though, like I said, I don't know code and could just be reading into this whole issue wrong.  If so then my apologies, no offence meant.  Love your mod and appreciate all the work you've done on it thus far.
