### ISSUE TITLE
Biogas engine don't transfer power to BC pump

### ISSUE THREAD

**Issue by PWaksman** [ForestryMC/ForestryMC#1691]
JAR:
- forestry_1.11.2-5.3.4.99.jar
- buildcraft-7.99.3.jar
- forge-1.11.2-13.20.0.2228-universal.jar

Minecraft 1.11.2

Problem: When attached direct to a Build Craft Pump, the Biogas engine running with Lava and Water, won't pump power out. The power keep accumulating inside the engine buffer

**Comment by LuigiHutch** [comment]
This is due to BuildCraft now using MJ. As BC is in alpha, the MJ api it is subject to change. Mezz has stated that he would like to continue support BC and Forestry will likely support MJ (see [here](https://www.reddit.com/r/feedthebeast/comments/4qz70t/looks_like_buildcraft_is_bringing_back_michael/d4ya95x/)). I assume this will happen once BC reaches its 8.0.x release and the MJ api (and the rest of the BC api) is considered stable.

**Comment by PWaksman** [comment]
Ohh, i see, thanks for the explanation!

**Comment by mezz** [comment]
That's correct. For now, Buildcraft is not complete/stable and Forestry should wait for the MJ API to be finalized.
