### ISSUE TITLE
[Request/idea] New bee house 

### ISSUE THREAD

**Issue by NightKosh** [ForestryMC/ForestryMC#1700]
Hello. I would like to ask you about small improvement in bee housing.
Currently there are 3 types of bee houses: 

- "Bee House" - basic type of bee house, which used only at the game strart or to prevent bees mutation. 
- "Apiary" - improved "bee house", which used almost for the end of the game. 
- "Alveary" - improved "bee house" for the late game stage.

Unfortunatelly there is an increadibly huge distance beetween "Apiary" and "Alveary". "Alveary" extremelly expensive, and requires a lot of time to be created(you need to get a lot of rare bees species, and a huge amout of its production) wich make this process booring. For sure "Alveary" provides a lot of awesome features, but if you are playing without any bees addons it becomes a little bit useless, cause it is much easier to get all "profitable" bees species without "Alveary".

So it will be great to have an additional type of "bee house" (for example 2x2 cube (not of alveary blocks)), something better than "Apiary" but not so usefull as "Alveary". It should make game progress smoother, a little bit easier(for the middle stage of game), and not so monotonous as now(especially untill your first "Apiary" created).

**Comment by SandGrainOne** [comment]
I personally really love the balancing. At least how it worked when I was playing the most. (Note that the base for comb production is the Alveary.)

- Bee house - Impossible to automate. Give slightly more combs than Apiary without frames (30% vs 10%). Boosts pollination chance in tree breeding (right?). Prevents mutations, but not trait transfers. Very good when trying to purify a new strain at any stage of the game. Ignoble queens don't die, also usefull at any stage of the game. This makes it possible to quickly make a small army of ignoble comb producers when you have your first Industrial or Imperial bee. Just safely transfer all traits from a pristine bee over to your stock of ingoble bees with a Bee House.
- Apiary - Bees can be automated, but frames must be added manually. Really bad comb production (10%), but automation makes them worth while. Manually adding frames gives a good boost to comb production (up to 70%). Can cause mutations. 
- Alveary - Bees can be automated. Makes it possible to keep almost any bee in almost any biome with the environment manipulators. Have 100% comb production without frames. (Causing massive storage problems...)

This is some of the best balancing I have ever seen from any mod in Minecraft. IMO!! :D 

Without additional mods it does take a few hours to obtain the two strains, Industrial and Imperial, required to craft the Alveary. I don't think this is unresonable. It's still a tiny fraction of the time you are going to spend finding new species if your goal is to have them all. If you have another mod that can help controll mutations you should be done in 15 minutes. (This is unresonable, but that is a different story.)

PS. This post was not directed solely at OP, but also to the current team of developer. I think it is very important that you guys understand fully how everything in the mod can be used and consider all change requests very closely before implementing changes.

**Comment by NightKosh** [comment]
@SandGrainOne Few hours? You need to get new 8 species of bees. Bee's life time more than 1 minecraft day, so it will take more than 15-24 minutes(and 3 times more if you use "Bee house"). Furthermore bees mutation chance rather low 12% - 8%. And you will need additional time to get stable bees species for all mutation steps. So lets count:
"required bees species" * "life time" * "chance" -> 8 * 15 * 10 = 1200 minutes (20 hours) 
but at practice it should takes even more time.

**Comment by NightKosh** [comment]
Anyway I'm not talking about required time to get "Alveary" or game balance. I'm asking about some intermediate step beetween "Apiary" and "Alveary", which should make progress in bees breeding more sensible.

**Comment by SandGrainOne** [comment]
Okay fair enough. I guess time flies when you're having fun.

One thing I find interesting with Forestry bee breeding is that it is more like a side project. The end result doesn't give you anything. The most usefull stuff is the Bags and you get that from basic tropical bees. Maybe that is why I've never been in any rush or noticed the time.

You've made your point and suggested a new type of housing for bees. The question is how it should work. I could say we need 100 new type of houses, but such an idea is useless without a plan for how the houses should be different in a way that answers the issues you have identified.

I would claim that if you play with mods like Binnies mods, then you already have everything you need. The question is if Forestry should try to do the same on its own?

**Comment by danielrossyamitrano** [comment]
> I would claim that if you play with mods like Binnies mods, then you already have everything you need

I play with binnie's mods (and many others) and still it took me days before I could build an Alveary. Even after messing with the config files (to make mutations 100% secure), it's still a long time and a lot of frames to get enough materials to build an Alveary with only 2 species that produce pollen and royal jelly (getting the necessary amount of honey is also a time consuming task)

**Comment by SandGrainOne** [comment]
Like I said. Please come with suggestions as to how adding a step will make things faster.

I'd like to point out that Alvearies are not a requirement. You can get every single species of bee without Alvearies. They do not change anything in relations to mutations. They can help you get mutations in the wrong biome, but apart from that they only boost production of combs.

If this is an issue raised because of Binnies mods adding all the different mutation modifiers and the frame block for the Alveary, then it is an issue that should be solved by Binnies mods. In that case I might even agree that the time it takes to get the first Alveary is a little long. Especially when considering how massive the species tree added by Binnies mod actually is, and how valuable the output from the bees can be.

**Comment by NightKosh** [comment]
> I'd like to point out that Alvearies are not a requirement. You can get every single species of bee without Alvearies. They do not change anything in relations to mutations. They can help you get mutations in the wrong biome, but apart from that they only boost production of combs.

You forget about stabilizer. It is incredibly useful to get stable species of bees, without wasting additional time by "Bee House".

**Comment by NightKosh** [comment]
> You've made your point and suggested a new type of housing for bees. The question is how it should work. I could say we need 100 new type of houses, but such an idea is useless without a plan for how the houses should be different in a way that answers the issues you have identified.

As you said beefore
>bee breeding is that it is more like a side project. The end result doesn't give you anything

so my idea was firstly to give some sense of progress in the way to alveary creation(cause you will spent huge amount of time just to get all those bees, without anything else). For sure it should give you some additional advantage, so it can provide more production than apiary, or maybe such improvements like "alveary stabilizer" do, or even "protection for ignoble bees" like in "bee house". Any way it will be great to have just production boost.

**Comment by SandGrainOne** [comment]
How would you prevent the new housing from completely replacing the Bee house?

**Comment by NightKosh** [comment]
> How would you prevent the new housing from completely replacing the Bee house?

Why it should be prevented? "Bee house" is an early game block. The only one reason to use it in a late game - it can prevent death of ignoble bees.

**Comment by SandGrainOne** [comment]
I'm keeping this discussion going mostly because I want to exemplify what kind of questions you are putting on the developer to solve. It is not unresonable to expect them to find answers to many questions like these themselves, they are game developers after all, but from time to time I want to put the player in the same shoes. Challenge you to defend your idea. 

In this case I was wondering more about crafting, or progression if you like. Unless the recipes has changed you can easily make Apiaries without ever having crafted a single Bee House. The value in the Bee house isn't as a stepping stone, but the features it holds. Copy those features to a new house type and what do you get?

**Comment by mezz** [comment]
I would like to avoid adding any new features to the mod. The greenhouse is still WIP and there is not enough time to maintain everything we would like to include.

I think the main issue with Forestry here in modern Minecraft is that it takes a long time compared to new mods.
The solution is probably to make the number of ticks in a bee life cycle configurable (`PluginApiculture#ticksPerBeeWorkCycle`) and possibly lower the default value a bit.

**Comment by SandGrainOne** [comment]
In a world where the Apiary can be very easily automated, players need to see the value of "shortest" lifespan...

**Comment by SandGrainOne** [comment]
I want to end this with a few tips:

Don't start any serious bee breeding before you have around 10 pristine princesses. As someone else pointed out there are 8 species up to Alveary bees and you would want to keep at least one princess of every type. You can use all your pristine and ignoble princesses to produce combs and even do some improvements into a breeding focused strain, but don't aim straight for the Imperial and Industrius bees.

One improvement you could try to make is to give as many princesses as possible a shorter lifespan to increase the retry fequency, but be prepared for the traits to reset when you get a mutation. 

Another even better improvement is to give the breeding strains a fertility of 4. 4 drones instead of 2 does wonders to mutation chance.

Ignoble bees have a chance to die in an Apiary, but the chance is relatively low and loosing one mundane or even cultivated ignoble princess isn't terrible. Just don't be tempted to do "just one more try" when you are getting into the better bees. 

Focus on making seed oil (or creosote) for Apiaries. If the math checks out and it takes 20 hours with one Apiary then you should be able to do it in 5 hours with 4. Also use Bee Houses of course.

If you managed to find about 10 pristine princesses you probably have at least 30-40 ignoble. Try to find uses for some of them. An ignoble Forest princes can be turned into a cultivated princess in a Bee House in just a few cycles if you already have some cultivated drones.

Never stop producing drones, use them to do research in the Escritoire. Every species you discover with the Escritoire improves the species mutation chance.

And by now you have probably used far more than 20 hours, but oh well, at least I had fun.

**Comment by NightKosh** [comment]
@mezz If the only problem to implement such feature is a lack of time, I could help you with it and implement it by self(if it is acceptable for "Forestry team").

**Comment by NightKosh** [comment]
> In this case I was wondering more about crafting, or progression if you like. Unless the recipes has changed you can easily make Apiaries without ever having crafted a single Bee House. The value in the Bee house isn't as a stepping stone, but the features it holds. Copy those features to a new house type and what do you get?

I'm not talking about to make alveary blocks cheaper, instead of it this new bee house should be made of its own type of blocks\items, which should be crafted with some "intermediate" resources. As for example/suggestion "Stringy Combs", "Dripping Combs"(may be you could create a "Stringy/Dripping Combs Chunk" ?), "Impregnated Frames" (or even "Proven Frames") and "Apiary block" can be used for this purposes. All those resources always available in a huge amount in the middle stage of game, so it can be reused as a components for new type of bee house. It is just a suggestion, I'm sure "Forestry team" may have better ideas about it.

**Comment by mezz** [comment]
I think the gap is fine, it is a big accomplishment to make your first Alveary. With practice (for players like SandGrainOne), it is easier.

The issue is not with the effort to add the new features, but the effort to balance, bugfix, and port things over time. The team is working on porting Binnie's mods right now and we do not have the manpower to take on any more features. We can barely keep up now.

For that reason I have to turn down this suggestion, and others that include new features. Sorry.

**Comment by SandGrainOne** [comment]
I suddenly actually got an idea for something to think about in the future. Limited **manual** climate control. It could be a way for the player to perform more breeding in the local climate.

We can discuss how this could be done once things have stabilized.

**Comment by mezz** [comment]
I think new ideas should be implemented as Forestry addons. The API is pretty powerful.

**Comment by NightKosh** [comment]
@mezz The last Forestry addon I created died almost at the same time as it was released. An important feature of the Forestry API was removed... (To be honest there were additional problem - update of my main mod for Minecraft 1.8 and higher takes too much time). 

Any way, as you said I can implement all those ideas as addon, but I'm not sure how long I'll be able to maintain it.(This is the reason I asked about it as a part of Forestry)

**Comment by mezz** [comment]
I think you are asking us to maintain something for you, but unfortunately we do not have the time either. If the API breaks, let us know and we can fix it.

**Comment by NightKosh** [comment]
Yes, I am. But I hoped such features will be interested for you.) Furthermore, as I think, it shouldn't really takes much time for it - all things I'm talked about already implemented in Apiary, Alveary and "Bee House". Anyway it doesn't matter as far as it is not acceptable for you.

As for API - there is an issue for it. But I'm not hurry with it - I'm still working on update for Minecraft 1.11.2 for my "main mod".
