### ISSUE TITLE
Not able to do Orchard with Pam's HarvestCraft 

### ISSUE THREAD

**Issue by LarsBorris** [ForestryMC/ForestryMC#1718]
Forestry 5.2.17.377 & Pam's HarvestCraft 1.9.4-1.10.2g (On DireWolf20 pack MC 1.10.2)

Orchard Manual Farm:
The farm is unable to harvest crops from Pam's Trees.
Trees like olives and peppercorn.

Usually you plant the tree and then the crops grow on the trees. (this is still the case)
Once the crops have reached mature growth-stage they will be harvested and drops down onto the farm base to be collected. However the crops just sits there at mature growth-stage and is not being harvested.

Have tried updating to newest version of both Pam's HarvestCraft and Forestry, however issue still persists.

Have some screenshots:
![screen shot 2017-06-24 at 17 17 56](https://user-images.githubusercontent.com/10630935/27509630-a823ff28-5901-11e7-93fd-a783208caef5.png)
![screen shot 2017-06-24 at 17 19 00](https://user-images.githubusercontent.com/10630935/27509634-aa3df138-5901-11e7-8122-b96bbc40942e.png)

**Comment by kschmalz** [comment]
Same issue.
I'm using forestry_1.10.2-5.2.17.377, Pam's HarvestCraft 1.10.2j in FTB Beyond v1.10.0


![multifarm1](https://user-images.githubusercontent.com/29682845/27512871-6f8f20f6-5916-11e7-906a-8195ecc5a4c9.jpg)

Nothing missing in the gui:
![multifarm2](https://user-images.githubusercontent.com/29682845/27512874-8055686e-5916-11e7-9960-b352aa843ba1.jpg)

**Comment by LarsBorris** [comment]
Bump?

**Comment by Nedelosk** [comment]
Fixed in 1.12
![2018-01-06_18 31 46](https://user-images.githubusercontent.com/10259214/34642230-decde036-f30f-11e7-9f62-55510186d88c.png)

**Comment by Rodg88** [comment]
Something with Pam's fruits seems to be broken again, the orchard mode farm is harvesting the actual fruit 'nodes', instead of collecting the products. It oddly enough replaces the harvested nodes too.
![2018-08-02_23 30 18](https://user-images.githubusercontent.com/2611674/43587483-ace44b0e-96ad-11e8-8bee-893afe8ce7a6.png)

The screenshot shows the harvested nodes in the farm output, instead of the fruit.

Tested in FTB Continuum 1.4.1, with forestry updated to forestry_1.12.2-5.8.1.326
