### ISSUE TITLE
[request] Make bees more usefull

### ISSUE THREAD

**Issue by winnetrie83** [ForestryMC/ForestryMC#1754]
While this is an interesting mod, i can't find any reason to be busy with bee breeding since it doesn't reward you with anything usefull, as far as i know. Honey, sugar,... I mean what's the point in breeding bees?
I'm sorry if this isn't the right place to ask this. I don't know where i should ask this instead.

**Comment by SandGrainOne** [comment]
It depends on what you are used to and what you compare it with. I would agree that Forestry has problems fitting into and fighting for your attention in large mod packs with a lot of other alternatives. (I have heard chicken breeding is the new craze. Diamond chicken anyone?)

Forestry has always tried to avoid making too many changes to the resource balance in a world. You can't get a bee that makes iron or diamonds in Forestry. It would mess up any resource balance other mods might rely on. It is a low impact mod that stand very well on its own or with a few friends. The disadvantage is that other mods can very quickly be considered "better". Especially by players who play for the resources instead of the work of building the system making said resources.

I can have a lot of fun making a system and when I am done I turn it off. That way I don't need to deal with all the resources they are making.

**Comment by winnetrie83** [comment]
Well i don't like big mod packs, especially all those overpowered stuff. Forestry looks very interesting. I like the idea of breeding bees and trees etc etc and get better types, but on the other side i also want it to be rewarding also. What can those bees produce that is rewarding? Sugar is a nice byproduct but nothing special. I heard breeding trees can result in trees that gives more fruit or something. Is there any list where i can see what the forestry bees can produce?
I also saw somewhere they can spawn flowers? Is that right?

**Comment by BionicFelps** [comment]
You can get lava from high tier bees that can be used in other mods assuming your pack has no way to drain the nether and transport it to the overworld. Also cheap torches, wax capsules, the ability to control the weather. All depends on bees.

**Comment by SandGrainOne** [comment]
Rewarding is relative to the player. I personally have fun with the Reanimate effect. This will for example spawn a Skeleton from a bone should it be lying on the ground close enough to a queen with the effect. A fun way of getting Wither Skeletons in The Nether. 

The wax capsules are actually one of the most effective storage methods for fluids. 1728 buckets in a single normal chest. Move massive amounts of fluids easily in your inventory.

Other things. Gunpowder for fireworks when flying around with your Elytra. Glowstone to light up your home. Make Crushed Ice, a super effective coolant for the BuildCraft Combustion engine. Make Lava, Ender Pearls.

As you can see, nothing rewarding.

**Comment by winnetrie83** [comment]
Reanimate effect? Does it do that with vanilla forestry? How do they produce the lava? Does it comes with a bucket? Besides that i'm playing in 1.12 so no buildcraft atm. There is also not much use for ender pearls. Not that i would need tons of it.

**Comment by SandGrainOne** [comment]
Reanimate comes from the Spectral species. Resurrection comes from Phantasmal. Both from Forestry. To produce Lava you combine Phosphor with dirt, cobble or sand in a Squeezer.

Anyway. Maybe you have some cool ideas that the development team could consider adding? Requesting changes are easy when you don't need to come up with the idea yourself.

Let us put it this way. Unless you have a relatively complete idea, then this is the wrong place to start a discussion. I don't know where the developers gather these days. When I was active it was on IRC.

**Comment by Obbi89** [comment]
If you want to go mental with forestry you can use more bees / gendustry etc.
All mods that add a lot of bee breeds that can produce almost any ore or gem from Minecraft.

**Comment by mezz** [comment]
Bees are very useful, it sounds like you just have to dig a bit deeper into it.
