### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by Thill199** [ForestryMC/ForestryMC#1768]
Shift clicking in the work table making signalum or any other TE stuff causes a massive dupe.
was able to get a clip of doing it

https://clips.twitch.tv/SuccessfulEntertainingPoultryPipeHype

**Comment by Thill199** [comment]
[1.12] version 1.12-5.4.3.137

**Comment by Vectrobe** [comment]
Just found this too, and it doesn't have to be shift-click either, the worktable simply cannot handle bucket recipes.

- crafting a bucket recipe expects the items and one full bucket to be used up, an empty bucket to be returned to either the player or craft inventory
- what actually happens here is a single craft will 'appear' to take one set of items and one bucket, subsequent crafts will not and you can infinitely duplicate the craft result
- if you exit the GUI and re-enter, the items 'reset', which basically means the items were never used in the first place, it's much like the craft inventory would be 'read-only'

**Comment by Vectrobe** [comment]
probably related to #1403

**Comment by Obbi89** [comment]
Seems to be a new bug. I cannot reproduce in 1.10

tbh I cannot reproduce this. There is a issue that looks like item duping but no Items get duped at all.
Or are you talking about the apparent duplication of items?

**Comment by Terpo** [comment]
Just tested it in 1.11.2 with this small modlist in SP:
Forge 2386
CodeChickenLib-1.11.2-3.0.0.284-universal.jar
ThermalDynamics-1.11.2-2.2.6.13-universal.jar
ThermalExpansion-1.11.2-5.2.6.22-universal.jar
CoFHCore-1.11.2-4.2.7.15-universal.jar
ThermalFoundation-1.11.2-2.2.5.16-universal.jar
ImmersiveEngineering-0.11-63.jar
forestry_1.11.2-5.3.4.135.jar
jei_1.11.2-4.5.0.294.jar

Interesting here is: It does work exactly one time and you get back your empty bucket. When Signalum is added to the "remembered recipes" it can not craft anymore at all. On my server with a version from two weeks ago I ran into the same major dupe bug as descriped above. 

On the other hand: Treatead Wood crafting from Immersive Engineering works perfectly! (8 planks & bucket of creosote)

Could that be caused because thermalfoundation:material uses a massive amount of metadata?

manual crashlog: https://gist.github.com/Terpo/b3612bfaf7ba1e246229ba5905dd2adb

**Comment by Thill199** [comment]
its almost not even a dupe bug its just a massive bug that nets loads of issues when trying to make a pack

**Comment by Obbi89** [comment]
The issue is related to the actual crafting of the item.
Somehow the FluidUtil.getFluidHandler method returns a FluidContainer that is empty and this causes no crafting recipe to match the ongoing crafting operation in CraftManager.getRemainingItems(). No matches causes *remaining items* to be the original input to the crafting operation. At the same time the crafting operation produces 4 * enderium dust causing an infinite crafting ability cause no items are consumed.

I'm not sure however why or where that ItemStack of BucketFilled gets corrupted or in what way it gets corrupted so that the FluidHandler returns an empty instead of full fluid container that cannot be drained of liquid ender and thus failing miserably in the process.

Further investigation is necessary by someone with more knowledge of the code base. I can give all my results and information if needed. Just hit me up on irc or wherever.

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next build.

The issue was that we were passing the real crafting grid to `getRemainingItems` and it was being altered by the fluid handler, which drained the bucket but did not update the crafting grid with the result.
Instead, we now pass a copy of the crafting grid so that it cannot be altered.

I also improved the algorithm for figuring out which items can be used as substitute ingredients in a recipe. Instead of heuristics, we now try substituting ingredients into the crafting grid one at a time and check that the recipe still accepts the arrangement as valid. This should solve most of the subtle worktable bugs we have encountered so far.
