### ISSUE TITLE
Worktable forgets recipes that involve minetweaker.

### ISSUE THREAD

**Issue by IMarvinTPA** [ForestryMC/ForestryMC#1778]
This isn't the absolute latest at this point, but I saw nothing in the change log that seemed to affect this.
Forestry 5.2.17.381 in Age of Engineering pack 1.0.4.  Minecraft 1.10.

My theory was that the table was forgetting newer recipes after your first use.  But upon trying to test that and failing.  My new theory is that the table tests the validity of the recipe on world load and mine tweaker changes it after this test.
I have done the recipe on the left several times, and it keeps getting forgotten on reload: ![2017-07-28_00 16 57](https://user-images.githubusercontent.com/4486117/28702363-68036760-732a-11e7-96a9-b6c735d0a6d1.png)

Can the table validate the recipes on access vice on load so minetweaker can have a chance to update before the table removes it?

Thanks,
IMarv

**Comment by mezz** [comment]
The worktable validates itself when the tile entity is loaded, its memory is stored there.
I think Minetweaker loads earlier than that but we can move the validation to when you access it.

This shouldn't be an issue in 1.12 because recipes have unique names and also because Minetweaker loads everything during startup.
