### ISSUE TITLE
Malisis anamtions support in 1.10?

### ISSUE THREAD

**Issue by Trinsdar** [ForestryMC/ForestryMC#1821]
do you think you will add support for malisis's doors animations or at least double door opening?

I don't care too much, I'm just wondering.

**Comment by mezz** [comment]
I think this may be up to Malisis's Doors, I do not know how it works.
Do other mods add their own integration?

**Comment by Trinsdar** [comment]
I remember reading request made a couple months ago by other people, and they(the mod team) said it was up to the other mods, not them

**Comment by mezz** [comment]
@Ordinastie is it possible to integrate Forestry's doors with Malisis's Doors?

**Comment by Ordinastie** [comment]
It used to be that I could add integration on my side because the block needed to be replaced, but maybe it's a bit more feasible now that substitutions actually work in Forge.
But you're willing to add integration on you side, it should be pretty easy and straightforward.
Don't hesitate to hop in #malisis if you want to talk about it.

**Comment by ElvenChaos** [comment]
I would love to see the integration available in 1.12.2! :D

**Comment by mezz** [comment]
This would be cool, but I discussed this with Ordinastie and unfortunately the integration would be somewhat complicated. The door blocks basically have to be replaced when Malisis's Doors is present. I have not really wanted to spend the time to do it because it will be tricky to implement properly and would take additional effort when testing and porting to new versions.

**Comment by Ordinastie** [comment]
I guess, short of making a PR myself, it won't happen, right ? =)

**Comment by mezz** [comment]
I think so, yeah.

**Comment by Nedelosk** [comment]
We currently don't have enough time to look into things like this. But feel free to make a PR your self.
