### ISSUE TITLE
[1.10.2] Can't use/setblock to place apiary

### ISSUE THREAD

**Issue by Alan19** [ForestryMC/ForestryMC#1834]
I get a purple and black block when I use/setblock to place an apiary or bee house

**Comment by mezz** [comment]
The default state when you place an apiary or bee house is "facing down" which is not normally obtainable, and it shows as purple and black.

You can get around this by adding a dataValue to the end of the setblock command.
`/setblock ~1 ~1 ~1 forestry:apiary 2` will place a valid apiary because the dataValue of 2 is facing north.

This is no longer an issue in the 1.12 version of Forestry.

**Comment by Alan19** [comment]
Thanks!

**Comment by Alan19** [comment]
Is there a way to use setblock to set apiaries with bees inside them? @mezz

**Comment by mezz** [comment]
I'm not sure if it's possible or not, I'm not that good at vanilla commands. It might be similar to spawning a chest with items in it.
