### ISSUE TITLE
Oak trees are not growing in a farm.

### ISSUE THREAD

**Issue by ZeroInputCtrl** [ForestryMC/ForestryMC#1862]
MC: 1.2.1 w/ dedicated server
Forestry: 5.5.6.197
Forge: 14.22.1.2485

I have the smallest farm setup outside surrounded by glass. I left this on for hours an no Oak Wood in my system. I've tried using bonemeal to force a tree to grow but with a full stack that didn't do anything. I do see randomly humus turning into sand, not sure if that's just random or if it happens after a specific event being triggered. 
http://prntscr.com/gqwy98
http://prntscr.com/gqwyml

The glass surrounding is TiC Clear Glass, so i broke away some of it with no effect on growth. When i have debug information up the sky light level is 15 under the glass. And a tree in just normal dirt successfully grew under the glass fine. Nothing in my server logs seem to indicate any issues.

**Comment by ZeroInputCtrl** [comment]
I've updated to 5.6.0.201 and nothing is still growing. Any ideas? Am i doing anything wrong, nothing in the interface is throwing a red flag.

**Comment by thecanidcoder** [comment]
I'm seeing the same thing. Trees are not growing on humus placed by the multifarm. I can go through ten full stacks of bone meal and nothing will happen. However, if I break the humus and place humus or dirt myself, I can bonemeal a tree out of it.

**Comment by thecanidcoder** [comment]
So my issue turned out to be caused by Recurrent Complex. REC adds custom sapling 'recipes' for it's big trees (like 2x2 giant jungle trees in vanilla), and these recipes break sapling clusters. If I put nine saplings together in a square, none of them would grow. I worked around this by using non-vanilla trees that didn't get affected by the recipe. 

Recurrent Complex' config file has an option ( S:saplingTriggerChance ) which is set to 1.0 (100%) by default. You may be able to work around this problem by reducing that chance or disabling it entirely. I haven't tried this yet, as the other workaround satisfies my needs for now.

**Comment by ZeroInputCtrl** [comment]
Huh, i do have that installed as well... i'll play with the settings i guess

**Comment by ZeroInputCtrl** [comment]
Although when i was playing 1.12.0 i think i had it as well, and it was just growing giant trees the whole time, no issue. Maybe it's trying to grow giant trees but the ceiling is too low?

**Comment by thecanidcoder** [comment]
My farm had no ceiling at all. 

I did eventually change the config to 0.5 (50%), and that solved the issue entirely for me.
