### ISSUE TITLE
Square Multifarms do not give equal space.

### ISSUE THREAD

**Issue by Loothor** [ForestryMC/ForestryMC#187]
Looking at the largest farm (17x17), north and south do not give equal room. See attached photos.

Thanks in advance! (also, I will be updating to fix the issues you see in the SSs)

![2014-09-14_18 01 01](https://cloud.githubusercontent.com/assets/8557476/4265706/a811358e-3c5b-11e4-85d0-846cfd2f8d44.png)
![2014-09-14_18 01 10](https://cloud.githubusercontent.com/assets/8557476/4265707/a8164998-3c5b-11e4-96a3-c2c58c14c806.png)

**Comment by BionicFelps** [comment]
Actually I think it makes sense that they're different sizes... I honestly need smaller farms for certain crops vs others... Reeds for instance, they grow rather fast, and get used less compared to, say, wheat or carrots... (in my games anyway...)

**Comment by ZacQuicksilver** [comment]
How much harder would it be to segment everything into 8 segments? That would give more flexibility, and probably easier to code.

**Comment by Flow86** [comment]
then you need a seed/soil slot for each segment, would be much better to handle it like that

**Comment by BionicFelps** [comment]
Oh, while we're on the subject of farms... I can't plant potatoes and carrots in the same farm, eventually one or the other will take over the whole thing!  This is because it always plants the first seeds first, maybe change it to a round robin thing, or even just separate carrot and potatoes into their own farms!

I have also taken note of the brain destroyingly complicated part, assuming they're not all hard coded it's probably easier just to make carrot and potato separate farm configs from each other...

**Comment by mezz** [comment]
Just about finished with implementing this.

@BionicFelps please make a new issue

**Comment by Sandriell** [comment]
What does the new layout look like?

**Comment by mezz** [comment]
It's kind of a pinwheel. Each side extends counter-clockwise.
