### ISSUE TITLE
[1.12.2] Wrech problem

### ISSUE THREAD

**Issue by Draskh** [ForestryMC/ForestryMC#1933]
In my modpack tech Reborn is also present. Forestry overwrites the wrench recipe. So cannot craft the wrench of Tech Reborn. But I need this wrench for mining the machines. Otherwise they break. 

forestry_1.12.2-5.7.0.219
forge 1.12.2 - 14.23.1.2562

**Comment by temp1011** [comment]
Using forestry 5.7.0.219, tech reborn 2.11.1.420.
![forestrywrench](https://user-images.githubusercontent.com/34900092/34481796-12cbd968-efac-11e7-8026-ee10e77e48ba.png)
![techrebornwrench](https://user-images.githubusercontent.com/34900092/34481797-17cef80a-efac-11e7-8b71-ddc1c1d13a89.png)
They seem to have different crafting recipes to me with no config changes. Also, shift right click with the forestry wrench picked up tech reborn machines for me.
I think this is an issue with your modpack rather than forestry.

**Comment by Draskh** [comment]
The recipe of the Tech Reborn wrench does not appear to me. If a Shift + right click in JEI it automatically change to the Forestry wrench. I'll take a look over it again.

**Comment by Draskh** [comment]
It seems that something with the unification wents wrong. I will need to edit the blacklist again to prevent this.
