### ISSUE TITLE
[Cross mod] Broken crafting recipe for harden casings allowing for dupe.

### ISSUE THREAD

**Issue by meelock** [ForestryMC/ForestryMC#1956]
https://drive.google.com/uc?id=1QAe-S8OvxFJhtRd4dAj_U6UPU5VXFPk6
<a href="https://imgur.com/BE5djMb"><img src="https://i.imgur.com/BE5djMb.jpg" title="source: imgur.com" /></a>

Modlist: https://hastebin.com/raw/hizejedexu
Log: https://drive.google.com/open?id=0B4qiuAniKLfHcTJ0UjZjNlJ0bWs

**Comment by meelock** [comment]
The dupe is fairly recent, thus it is either a new mod added to my modpack or one of the recent versions of forestry's fault. I am testing currently.

**Comment by ardaniel** [comment]
I have this problem, but it's tin cans in every crafting output, and it started when I updated Forestry and a few other mods yesterday. I _haven't_ recently updated Baubles, though, so maybe Baubles can be ruled out, since I have the same version you do (1.12-1.5.2). I do have the same version of Forestry (1.12.2-5.7.0-236).

I'm rolling back Forestry in my modpack to -232 to see if this resolves.

**Comment by ardaniel** [comment]
It's not Forestry-- I rolled back and it kept happening-- it's Platforms. I removed Platforms (based on a comparison of your recently-updated mods and mine; thanks for the list!) and my issues resolved, related to:
https://github.com/ShetiPhian/Localizations-and-Issues/issues/140

**Comment by meelock** [comment]
Thanks so much for the info!
