### ISSUE TITLE
[1.12.2] Greenhouse climate sources don't work

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1977]
I tested greenhouse in forestry 5.8.0.242. But all climate sources show me error message, no matter what the size of the multiblock (I built 3x2x3 and 5x5x5).

![image](https://user-images.githubusercontent.com/1331559/35643019-0479bbd2-06d6-11e8-86ac-82910ea09eec.png)

![image](https://user-images.githubusercontent.com/1331559/35643026-0c6a8c72-06d6-11e8-8da9-bb4437260c19.png)

Did I do something wrong?
I used info from https://github.com/ForestryMC/ForestryMC/issues/1849

**Comment by Lethann** [comment]
For starters I don't think those go in the wall, ~~I think they go inside  of the multiblock structure itself.~~ (see below) I couldn't get power to it until I destoyed one of the bricks and put in the energy block. Same with 
, I think they go inside  of the multiblock structure itself. I couldn't get power to it until I destoyed one of the bricks and put in the energy block. Same with controller and screen. The one post that had all the screenshots in it showed the multiblock as a platform with the glass above it, but I'm beginning to think that's wrong and that the structure should go inside the glass. Sorta like a little shack inside the greenhouse. Someone please correct me if I'm wrong. I saw another screenshot somewhere and that's how it was. Been testing this on my sandbox creative world.

Frankly it's really frustrating that there isn't even a barebones "this is how to make a greenhouse (ALPHA AND ABLE TO BE CHANGED AT A MOMENT"S NOTICE)" page. Having to hunt around the net means incorrect info and unreliable testing. *sighs* Please devs make a simple page for it?

**EDIT**
Ok after fiddling for hours I finally hit on it. If you stand on the top of the structure and look up you should see the outline of some empty blocks. Those are where the climate blocks go. Its easiest to see with the heater because some red bars light up on it. The humidifier turns blueish when it's running but barely noticeable from non-working. 
![2018-02-10_00 08 08](https://user-images.githubusercontent.com/25929754/36059100-91fed9e8-0df6-11e8-930d-715ba6467d00.png)

 ~~So far I can only get two to work, the heater and the humidifier. The heater outputs WELL, the humidifier sucks. I can't seem to get it to raise it above normal even with a circuit board with four humidity II tubes on it. ~~

**EDIT 2**

Ok, so I'm an idiot. So I figured out why the second row of blocks wasn't working, I was putting them directly above the center green block and it wasn't liking it. Anywhere around it they worked. However the Humidifiers didn't like being directly on top of the structure though the heaters did. Fans work though I don't really know what they do? Couldn't get the hydroregulators to work no matter where I put them. *sighs* Hope this helps you. 
![2018-02-10_00 17 57](https://user-images.githubusercontent.com/25929754/36059189-84cf6ce0-0df8-11e8-9798-676054fd6ab2.png)

**Comment by KorDum** [comment]
Oh thanks for hard work! I'll try place blocks within greenhouse instead in side.

**Comment by KorDum** [comment]
![image](https://user-images.githubusercontent.com/1331559/36059722-686fd48a-0e4e-11e8-8176-ce16bafaeb92.png)

It works! Energy Distributor, Control and Screen must be at bottom of central construction, but Hydroregulator, Heater etc must be at side or inside greenhouse.
