### ISSUE TITLE
Hives causing performance issues

### ISSUE THREAD

**Issue by Sir-Will** [ForestryMC/ForestryMC#2060]
hey,
any chance this can be improved?

forestry_1.12.2-5.8.0.250

![](https://i.imgur.com/rPkfVZF.jpg)

**Comment by temp1011** [comment]
If this can be moved without causing issues probably because then most of that won't happen every tick. However, I'm sure mezz had good reasons for keeping them outside.

https://github.com/ForestryMC/ForestryMC/blob/54a9da917dc09cc6e7800001cd1eee7320021da1/src/main/java/forestry/apiculture/WorldgenBeekeepingLogic.java#L95-L96

**Comment by temp1011** [comment]
Also, was this while generating new chunks?

**Comment by Sir-Will** [comment]
No, world was pre-generated.

**Comment by temp1011** [comment]
This should be improved now

**Comment by temp1011** [comment]
Hey, did you ever re-run the profiler? Has this actually helped or are hives still causing performance issues for you? Just curious to see if there was a good impact.

**Comment by Sir-Will** [comment]
Unfortunately there was no modpack update yet. I have to wait for the modpack to update forestry.

**Comment by temp1011** [comment]
Has it updated now?

**Comment by Sir-Will** [comment]
Just checked and I couldn't find it in the snapshot at all. I assume your fix improved it a lot, thanks.

**Comment by temp1011** [comment]
No problem
