### ISSUE TITLE
[1.12.2] Server Crashes On Content ID Conflict with Apiarist Profession

### ISSUE THREAD

**Issue by dmitri-mcguckin** [ForestryMC/ForestryMC#2115]
Server is in the latest version of Forestry, as far as I know: `forestry_1.12.2-5.8.0.256.jar`

Players would repeatedly go exploring and hapenstance upon a village, when a village apiarist would be constructed. Then the server would crash each time a player came across a new village.

```
MC Version: 1.12.2
Forge Version: 2627
Forestry Version: 5.8.0
```

**__[Crash Log](https://gist.github.com/dmitri-mcguckin/bbde48b717102c7cd59e1af3bb188beb)__**

**Comment by temp1011** [comment]
~~https://minecraft.curseforge.com/projects/forestry/files/2556715 try .280. I believe there was a crash due to villager apiarist when I introduced a new feature that was fixed. Also try without sponge.~~

From the crash at first glance, this doesn't seem to be the same as https://github.com/ForestryMC/ForestryMC/issues/2040

I would try without sponge, sorry got confused.

**Comment by dmitri-mcguckin** [comment]
This issue can be closed, I later determined that this is actually an issue with SpongeForge's Villager Registry, and not specifically Forestry.

I do however have another separate issue that I will open in a new thread at some point.

**Comment by liach** [comment]
Yeah, a spongeforge update would fix this.
