### ISSUE TITLE
Charcoal Pit crashes the game on the newest build (+ModTweaker)

### ISSUE THREAD

**Issue by Agrax** [ForestryMC/ForestryMC#2286]
https://pastebin.com/9MVB3YRp

The newest forestry, the newest modtweaker. Tried to set the vaule below zero:

`mods.forestry.CharcoalWall.addWall(<minecraft:dirt>, -4);`

It really doesn't like negative values. Might be intended, but Rongmario asked me to post it here.

It doesn't crash at start. It crashes when the logs are almost finished cooking and are just about to be ready

**Comment by pyure** [comment]
Hiya Forestry Team, just to expand on above (same team):
* forestry_1.12.2-5.8.2.358.jar
* modtweaker-4.0.15.jar
* We're exploring ways to reduce the amount of charcoal per woodpile (w/o changing the wood pile recipe itself ideally)

**Comment by Rongmario** [comment]
That's a very shoddy fix. This means by default all recipes would result in at least 9 charcoal.

**Comment by pyure** [comment]
Is the 9-charcoal issue due to the "bonus" charcoal or the "base" charcoal generated?
Perhaps we should generate a separate issue and/or PR to allow users to config the "base" amount generated.

**Comment by Nedelosk** [comment]
Already fixed with cc89a55942f92134934a79880840b91a435cc0a4 and 341edd76197f85ed065edfe6184973b2f44dc5aa. The new range is from -9 up to 54.

**Comment by Xavion3** [comment]
I think these may be implemented incorrectly, per [here](https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/arboriculture/blocks/BlockAsh.java#L77-L78) the resulting ash blocks only give drops if the AMOUNT NBT tag is positive, but you removed the line of code which sets that tag using your new approach to determine charcoal output which isn't based off that tag. You may want to make that bounds checking function off startAmount instead, or otherwise remove it.

**Comment by Nedelosk** [comment]
@Xavion3 `AMOUNT` is not an NBT value it is a block state property any only contain positive values from 0 to 15. [I use 4 blocks that each are used for a different range of charcoal amount.](https://github.com/ForestryMC/ForestryMC/blob/341edd76197f85ed065edfe6184973b2f44dc5aa/src/main/java/forestry/arboriculture/blocks/BlockRegistryCharcoal.java#L59) 0: `0-15`, 1: `16-31`, 2: `32-47`, 3: `48-63`. Nine gets added to the charcoal amount of the wall block and because negative nine is the smallest valid value the smallest amount that can drop is zero.

**Comment by Xavion3** [comment]
Ah, understood. While you're at it then a closely related part, currently any unspecified block counts as a modifier of 0 as that is the default return value for getCharcoalAmount if no wall is matched, but that renders negative modifiers useless if you can just grab any random block and get better results. 

Unless there is something I've missed which makes non-specified wall blocks invalid with the recent changes?

**Comment by Nedelosk** [comment]
@Xavion3 I think a config option for the base amount would be a good fix for that problem.

**Comment by Nedelosk** [comment]
@Xavion3 Done https://github.com/ForestryMC/ForestryMC/commit/d9370109eca6b92a306e3b330c2365720f44995b
