### ISSUE TITLE
Propose: Adding Manual translation for zh_tw from zh_cn

### ISSUE THREAD

**Issue by zetaraku** [ForestryMC/ForestryMC#2291]
@3TUSK Hello! I'm a little Minecraft player from Taiwan :)

I have made up a bunch of outdated translation for zh_tw recently.
I also found that there is no translation of **Forestry Manual** for zh_tw (Traditional Chinese), and there's one for zh_cn, which was translated by you :)
Thinking of the players in Taiwan needing translation, would it be proper to take the Simplified Chinese version and use a translation program to translate it into Traditional Chinese?

https://github.com/ForestryMC/ForestryMC/compare/mc-1.12...zetaraku:manualcopy-zh_tw

Feel free to take this and commit it yourself, since I don't own any credit for this translation.
I would take care of the remaining follow-up adjustment for it.

**Comment by 3TUSK** [comment]
Greeting @zetaraku and apologize for late reply. School work is always busy and prioritized here because I really don't have a choice.  
Regarding translation of manual. I personally consider all my translation work is in public domain, so just feel free to make a `zh_tw` version based on that. For 99% of times I don't really trust machine translator, even if it's something like `zh_cn` -> `zh_tw` where the differences are minor (comparing with `en_us` -> `zh_cn`). As such, I hope that you can manually review the translation if you have some spare time. I am not very familiar with Traditional Chinese, so I can't really offer help on that.

<details>
<summary>简体中文</summary>
你好@zetaraku！最近学业繁忙，所以没能及时回复，还请见谅。  

关于手册翻译：我个人是把我的翻译看作是进入公有领域的，所以如果有需要的话可以直接拿去用。不过我基本上是不信任机翻的（包括简转繁，因为涉及到一些具体用词的差异），所以我觉得，有时间的话还是手动校对一遍更好。我本人对繁体中文不是十分熟悉，所以在这上面我帮不上什么忙，望理解。
</details>

**Comment by zetaraku** [comment]
Hi @3TUSK! Glad to see your reply and thanks for approving my proposal. :)
I know that machine translation has issues about wording differences between zh_cn and zh_tw.
Therefore, all machine translations will be reviewed and polished by me before making a PR,
so don't worry about that. ;)

**Comment by Nedelosk** [comment]
@zetaraku Any update on this?

**Comment by zetaraku** [comment]
@Nedelosk Sorry for keeping the PR opened for such a long time. I'll continue the translating today. :no_mouth:

**Comment by zetaraku** [comment]
The translation is work in progress:
https://github.com/zetaraku/ForestryMC/commits/issue-2291

**Comment by zetaraku** [comment]
This issue was resolved in PR #2486
