### ISSUE TITLE
[feature] Farm surface atop farm structure

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#233]
Hello,

Would it be possible to enable farm surface/soil atop farm structure trunk?

**Comment by BionicFelps** [comment]
I imagine it is the way it is just so that in all farm configs the center region is unplantable, if having the structure on the top I imagine this would still be the case... Although you could use the space for a regular old minecraft farm...

**Comment by mezz** [comment]
Unfortunately, after doing a lot of work on the farm, I don't think there is a good solution for this. 

A 3x3 or 4x4 top surface doesn't easily split into 4 sides, and adding a 5th "side" for a small patch would not work well with the current interface, and the side would be much smaller than the others. 

For farms of all one type it would work well, but I'm reluctant to add any special cases to the farm because the code is extremely complicated and prone to programming errors, even after refactoring.
