### ISSUE TITLE
Update CLA

### ISSUE THREAD

**Issue by Rupurudu** [ForestryMC/ForestryMC#2355]
CONTRIBUTING.md, CLA.txt and https://cla-assistant.io/ForestryMC/ForestryMC still contains old CLAHub.com link. 

Please update those to the new cla-assistant.io link and delete https://www.clahub.com/agreements/ForestryMC/ForestryMC if posible.

**Comment by Rupurudu** [comment]
@mezz

**Comment by mezz** [comment]
Thanks for the report!

I have updated the links to point to `cla-assistant.io`.

I left the `clahub.com` page up. Unfortunately, it requests a large number of permissions on my github account in order to log in to it, and I do not know the new maintainer or trust why they would require so many permissions. Since nothing really links to it any more, I think it's ok to leave it there.
