### ISSUE TITLE
Some Fence Gates is invisible in JEI and Inventory

### ISSUE THREAD

**Issue by Sunekaer** [ForestryMC/ForestryMC#2388]
Spruce, Birch, Jungle, Acacia and Dark Oak Fireproof Fence Gates is invisible in JEI and Inventory

> Mods:
  AE2WTLib-1.12.2-1.0.6
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv6-stable-6
  architecturecraft-1.12-3.80
  astralsorcery-1.12.2-1.10.11
  AttributeFix-1.12.2-1.0.4
  AutoRegLib-1.3-26
  Baubles-1.12-1.5.2
  bdlib-1.14.3.12-mc1.12.2
  bedpatch-2.2-1.12.2
  BetterBuildersWands-1.12.2-0.13.1.269+13450ff
  BetterFps-1.4.8
  binnie-mods-1.12.2-2.5.1.188
  BiomesOPlenty-1.12.2-7.0.1.2425-universal
  blockcraftery-1.12.2-1.2.0
  blocklayering-1.12.2-1.0.2
  bonsaitrees-1.1.2-b144
  Botania r1.10-360
  BuildingGadgets-2.6.6
  Chameleon-1.12-4.1.3
  Chisel-MC1.12.2-0.2.1.35
  chiselsandbits-14.30
  ClientTweaks_1.12.2-3.1.11
  CodeChickenLib-1.12.2-3.2.2.353-universal
  CoFHCore-1.12.2-4.6.2.25-universal
  CoFHWorld-1.12.2-1.3.0.6-universal
  CompactStorage-3.1-12
  Controlling-3.0.6
  CraftingTweaks_1.12.2-8.1.9
  CraftPresence-1.12.2-1.5.0
  CraftTweaker2-1.12-4.1.15
  CreativeCore_v1.9.40_mc1.12.2
  CTM-MC1.12.2-0.3.3.22
  CustomMainMenu-MC1.12.2-2.0.9
  DefaultOptions_1.12.2-9.2.8
  diethopper-1.1
  DynamicSurroundings-1.12.2-3.5.4.3
  emcbuilderswand-1.12.2-1.2
  EnderStorage-1.12.2-2.4.5.135-universal
  engineers_doors-1.12.2-0.8.0
  ExtraBitManipulation-1.12.2-3.4.1
  fairylights-2.1.5-1.12.2
  fancylamps-1.1.0
  FastFurnace-1.12.2-1.2.1
  FastWorkbench-1.12.2-1.6.1
  flatcoloredblocks-mc1.12-6.7
  foamfix-0.10.3-1.12.2
  forestry_1.12.2-5.8.2.387
  Forgelin-1.8.2
  FTBLib-5.4.1.88
  FTBUtilities-5.4.0.85
  FTBUtilitiesBackups-1.0.0.2
  furniture-6.2.0-1.12.2
  ImmersiveEngineering-0.12-89
  InventoryTweaks-1.64+dev.146
  itemzoom_1.12.2-1.11
  jei_1.12.2-4.15.0.269
  JustEnoughEnergistics-1.12.2-1.0.6
  JustEnoughIDs-1.0.2-26
  JustEnoughResources-1.12.2-0.8.9.48
  letsencryptcraft-1.10.2-1.2.0
  LittleTiles_v1.5.0-pre127_mc1.12.2
  MainMenuScale-1.3.2
  malisiscore-1.12.2-6.5.1
  malisisdoors-1.12.2-7.3.0
  Mantle-1.12-1.3.3.42
  MarbleCraftingTable-1.0.1
  minetogether-1.10.2-2.1.3
  modnametooltip_1.12.2-1.10.0
  modtweaker-4.0.16
  morebeautifulbuttons-1.12.2-1.7.3.20
  moreoverlays-1.14-mc1.12.2
  MouseTweaks-2.10-mc1.12.2
  MTLib-3.0.6
  mysticallib-1.12.2-1.1.1
  Neat 1.4-17
  NoMobSpawningOnTrees-1.2.2-mc1.12.2
  notenoughroofs-1.12.2-0.8.0.0
  OpenBlocks-1.12.2-1.8
  OpenModsLib-1.12.2-0.12.1
  OreExcavation-1.4.137
  OreLib-1.12.2-3.5.2.2
  p455w0rdslib-1.12.2-2.0.36
  ProjectE-1.12.2-PE1.4.0
  Quark-r1.5-146
  randompatches-1.12.2-1.15.0.1
  randomtweaks-1.12.2-2.4.3.2
  reauth-3.6.0
  RebornCore-1.12.2-3.13.6.424-universal
  RedstoneFlux-1.12-2.1.0.6-universal
  ResourceLoader-MC1.12.1-1.5.3
  ServerLevelType-1.2
  simplybackpacks-1.2.0
  simplylight-0.6.0
  SmoothFont-mc1.12.2-1.16.2
  snowvariants-1.12.2-1.0.1
  SplashAnimation-0.2.1
  StoneChest-1.0.4
  StorageDrawers-1.12.2-5.3.8
  TConstruct-1.12.2-2.12.0.115
  Thaumcraft-1.12.2-6.1.BETA26
  ThaumicJEI-1.12.2-1.5.5-23
  theoneprobe-1.12-1.4.28
  ThermalCultivation-1.12.2-0.3.2.11-universal
  ThermalDynamics-1.12.2-2.5.4.18-universal
  ThermalExpansion-1.12.2-5.5.3.41-universal
  ThermalFoundation-1.12.2-2.6.2.26-universal
  ThermalInnovation-1.12.2-0.3.2.11-universal
  TinkerToolLeveling-1.12.2-1.1.0
  TipTheScales-1.12.2-1.0.3
  topaddons-1.12.2-1.10.1
  torchmaster_1.12.2-1.7.1.74
  twilightforest-1.12.2-3.8.689-universal
  UniDict-1.12.2-2.9.2
  UnlimitedChiselWorks-0.2.0
  UnlimitedChiselWorks-Botany-0.1.2
  Vanilla Builders Extension-1.12.2-1.0.8
  WanionLib-1.12.2-2.2
  WirelessCraftingTerminal-1.12.2-3.11.88
  Xaeros_Minimap_1.16_Forge_1.12
  XaerosWorldMap_1.3.3_Forge_1.12
  XenCraft-1.0.0.1
  Xtones-1.12-1.0.8-11
  YABBA-1.1.2.45
  YAMDA-1.0.2

**Comment by temp1011** [comment]
![jei](https://user-images.githubusercontent.com/34900092/55241831-e167d980-5233-11e9-9fb4-d2fab50c65c2.png)
I can't tell you which mod in the list causes issues but with just forestry and JEI things work fine.

**Comment by sealchan1** [comment]
In 1.12 it looks like an old issue with having so many possibilities in craftable fences in Binnie's Extra Trees caused severe lag.  I suspect that the solution was to add code into Binnie's Extra Trees (that used to be a separate mod (see https://ftb.gamepedia.com/Binnie-Fix)) that disabled most of the 65K+ recipes so that lag would be prevented and then they added code that worked like another mode (see https://ftb.gamepedia.com/Binnie_Fence_Recipes) that somehow dynamically allowed those crafting recipes to still work.  I suspect that the normal methods JEI uses to parse recipes won't pick up on these.

So far the recipes on their wiki seem to work barring recipe conflicts (like Quark's Chute which blocks all of Binnie's Full Fence recipes).  Unfortunately, with this state of affairs you cannot go into creative mode to cheat in certain fences due to their not being visible in JEI.

https://binnie.mods.wiki/wiki/Fences

**Comment by Nedelosk** [comment]
@sealchan1 These Binnie's Extra Trees Fences and Forestry Fences are generated totally differently and they have nothing to do with this issue. If you have an issue, please report it at https://github.com/ForestryMC/Binnie.

**Comment by sealchan1** [comment]
I didn't report this issue.  I was merely trying to explain what I had discovered that might go toward explaining this issue based on my own experience.  It appeared to me that no one had been monitoring Issues in quite some time. 

I have reported an issue with the Fence recipes in the Binnies area.  I also did some research in the code to try and identify what I thought the issue was.  Same for an issue with Botany which seems to be not working in a basic way for quite some time as even evidenced in a couple of newer mod videos.  I hope that you are back and are going to be able to work on these items.

I myself am setting up my own mod authoring environment and hope to learn how to create mods.  I might be interested in volunteering my time to help provide actual fixes to those mods, especially those that see a large amount of time between updates.

**Comment by gwynhefar** [comment]
Was this issue ever solved? Because I'm having the same problem. The gates place properly, but the inventory icon is completely blank.  It's only an issue in that I like to use the Storage Drawers mod to keep my building materials organized and with no inventory icon there's no way to see which gates are in which drawer.  If there's an easy fix I'd love to know.
