### ISSUE TITLE
Is there a release planned for 1.19.2?

### ISSUE THREAD

**Issue by nikrokss** [ForestryMC/ForestryMC#2715]
Thanks in advance for your answer

**Comment by ramidzkh** [comment]
From us? Not for a month at least. I heard there's another guy whose ported Forestry to 1.19.2, https://github.com/TheCricket/ForestryMC/tree/dev/1.19.x, but don't expect too much

**Comment by litjohn50** [comment]
I'll further this question aswell. 1.19.2 does seem weird since its not the latest. What version are you guys thinking of porting aka latest version. 1.20 or the next big mc release or even after that?

Or are you waiting for the whole thing with neoforge to be useable on curse like some other mods I have talked too?

**Comment by FrozenGalaxy** [comment]
Any news on this? Are you guys targeting 1.20.5+? NeoForge?

**Comment by PR0J3CT12** [comment]
Ic2 for 1.19.2 is here
Community is waiting for forestry and extra bees :D

**Comment by thedarkcolour** [comment]
https://www.curseforge.com/minecraft/mc-mods/forestry-community-edition
