### ISSUE TITLE
Suggestion: Accelerate Leaf Decay in Arboretum

### ISSUE THREAD

**Issue by lOmicronl** [ForestryMC/ForestryMC#282]
This is a minor suggestion that occurred to me while playing with Thaumcraft's axe of the stream... when you chop a tree with that, then in addition to all the wood being harvested, the leaf blocks of the affected tree decay at a greatly increased speed. Usually within 15 seconds, there are none left.

This reminded me of an issue... well, more precisely an *inconvenience* that I sometimes have with multifarm arboretums, especially when farming trees with naturally low sapling yield, like balsa. Some saplings generated from decaying leaf blocks are lost because they land on other leaf blocks that take more than five minutes to decay (or at least take long enough for a different tree to grow and interpose its leaves), causing the saplings to despawn naturally before the farm has any chance to collect them.

At other times, with other tree types, a multifarm may be enveloped in a permanent cloud of leaves because new trees grow before old canopies have a chance to decay. This is especially relevant with very large farms, and the recent version made all farms very large indeed. As a result, a significant number of old leaf blocks gets replaced by new ones upon a tree growth, resulting in noticably less leaves compared to "competing solutions" (*snicker*) that harvest the leaf cloud along with the tree. It also makes the farm area very inconvenient to access.

Thus I'm proposing an enhancement where the arboretum will accelerate the decay rate of leaf blocks just like the axe of the stream does. Of course, the effect doesn't have to be as drastic, if there's a potential performance concern (but still, it's not like other mods have problems with their autofarms breaking large canopies in seconds). Maybe a straight doubling over vanilla's speed?

This totally isn't a big deal, it's just a nice-to-have thing. :) But I think it would be a boon to Forestry's multifarms in the eyes of many players, who have often complained that Forestry farms don't process the leaves like other mods do and cause weak computers to suffer FPS degradation from large, permanent clouds of semi-transparent leaf blocks.

**Comment by VileTouch** [comment]
if i remember correctly, the accelerated decay already exist in Forestry trees. but you have to breed with a specific tree from extra trees that sheds all the leaves as soon as the first one is broken. the tree in question is the Common Elm. for it to be breed-able though, your semi-final sapling must be a pure (active+passive) Blue Mahoe with all the desired traits already included. this is because the chances of transferring that trait without losing any of the other ones is extremely low. (assuming you have been breeding a flawless tree the list of traits should be already full).

your resulting tree should be a pure mahoe tree that start falling apart as soon as you break one leaf block and is completely "bald" in 1.5mins or so.

another thing: after that there's no way of inter breeding this tree with any other without losing something, so it's advised to isolate your farm in a (very large) glass case and remove any other saplings, bees and butterflies  from the system

**Comment by mezz** [comment]
Forestry trees should work with the [FastLeafDecay mod](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2196219-fastleafdecay-leaves-be-gone). 
If you need faster decaying leaves, give it a try.
