### ISSUE TITLE
Item duplicating by letters

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#455]
video: https://www.youtube.com/watch?v=tQo5nY2HhMc
forestry_1.7.10-3.3.0.410-unstable
Forge 10.13.2.1286

**Comment by mezz** [comment]
Thanks for the report!
The item inventories do a "purge" when they close, spitting out any invalid items. The redstone should not be getting rejected by that check, and if it was it shouldn't stay in the inventory. I'll make this a high priority.

**Comment by mezz** [comment]
There were two ways to fix this:
1. make a special case for the received letter, since it's the only item inventory with locked slots
2. remove the purge code that spits out invalid items

I decided to go with number 2. Its purpose was to remove invalid items from backpacks when you close them. However, the inventory code is much more strict now, and can not accept "invalid" items in the first place (the slots and the purge code have the same definition of invalid). Keeping it around would be error prone for no benefit.
