### ISSUE TITLE
Carrots and potatos in the same multifarm

### ISSUE THREAD

**Issue by BionicFelps** [ForestryMC/ForestryMC#498]
Carrots and potatoes are planted in the same farm type, so it's impossible to have an automated farm that produces both, as if carrots are in the first seed slot, it will always plant carrots... likewise for potatos.  I readily admit this is a bit nitpicky, as I could just as easily create two multifarms...

Suggested fixes:

* Always replant the same seed as what was planted there before.
* Give potatoes and carrots separate farm config tubes
* Select seeds in a round-robin fashion

My favorite solution is for the two to have their own, separate config, so I could have, say, half the farm planting potatoes and the other half planting carrots.

**Comment by leagris** [comment]
Or:
* Get a tech upgrade with ghost item programmable chips ;)
* Overall rework multifarm, with 9 equal areas, 9 chips, and soil over
trunk (avoid dealing with complex uneven areas.

**Comment by erima** [comment]
I rather like the way that EnderIO locks a crop to a slot/section. Tubes and circuit boards seem to be the Forestry way of doing such things. I bring up the EnderIO method because it may be relevant to addressing this problem with a larger subset of similar crops, eg Harvestcraft food. Perhaps food types get locked when circuit boards are created?

**Comment by Nirek-K** [comment]
Addressed by #616
