### ISSUE TITLE
Add UBC worldgen to forestry backpacks

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#578]
We already have an Underground Biomes plugin, but the backpacks don't know to pick up its worldgen.

**Comment by asiekierka** [comment]
We don't anymore. Heh.

**Comment by Adaptivity** [comment]
Is it possible to create plugin which automatically find things like basalt, granite, marble, limestone etc? I've used Digger Backpack only few times and not sure how it's works(Not sure how it determines what it can pick up and what can't). And since there are a lot of mods which adds stuff like basalt, granite, marble, limestone maybe it possible to automatically detect them?

**Comment by mezz** [comment]
Currently it's pretty permissive and uses the ore dictionary. If something matches an oredict name of an item it is supposed to pick up, it'll work.
If we wanted to be even more loose, we could have it pick up blocks that have certain materials like "stone" but then we'd pick up all kinds of wrong things.
It would be best if mod authors used the ore dictionary to indicate that their blocks are like stone, but they might good have reasons not to (crafting).
