### ISSUE TITLE
2-Layer Farms

### ISSUE THREAD

**Issue by Chinthor** [ForestryMC/ForestryMC#626]
With the size of the central farm structure, it seems like this should work. And at first it leads one to believe it.

If all layers, from just below the farm up to level with the top, are valid for base material; why cannot the farm support two entire layers?

Building it to use the bottom-most layer first, it fills in with water and soil. After establishing that layer of farm, adding another layer of base material at the top causes the farm to stop all operations below and build a new farm layer above. But the lower layer is now abandoned permanantly. The leftovers are not harvested, nor is the soil reclaimed.

Can this be changed?

![2015-04-16_08 17 05](https://cloud.githubusercontent.com/assets/8145428/7181537/1955862a-e411-11e4-8b8e-2c3902f25189.png)

**Comment by mezz** [comment]
The farms are meant to be one level only. Since we support trees and tall plants from mods, there is no sane way to support multiple levels in the code without adding a lot more complexity.
However, the farms in 1.7.10 have been made to cover a much larger area than before. The one in your picture is small compared to what is now possible.
