### ISSUE TITLE
Add Apiary Cart

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#699]
[A good suggestion on Reddit.](http://www.reddit.com/r/feedthebeast/comments/37v3is/what_mods_make_forestrybinnies_better/crqcrz8)

Think about it, bees carts rolling all over the place. 
Guard bees, healing bees, growing bees, all zooming around.

🐝
🚃

**Comment by Vexatos** [comment]
But... How to manage the "nearby flowers" / "correct biome" and things like jubilance which take definitely requires the housing to be a block?

**Comment by laz2727** [comment]
As if entity cannot do it.

2015-06-04 13:32 GMT+06:00 Vexatos <notifications@github.com>:

**Comment by mezz** [comment]
The bees that require a resource under them would not be jubilant, you would still have the effect, just no special products.
Carts still have a position, the flower check and biome check would not be an issue. It might be wrong for a couple seconds at most.

**Comment by laz2727** [comment]
Maybe check what's below the rails for these bees?

2015-06-04 13:43 GMT+06:00 mezz <notifications@github.com>:

**Comment by mezz** [comment]
If I have the cart report its position as the position of the rails, that would work. I don't see why not.

**Comment by Vexatos** [comment]
@mezz The problem is that the cart changes its position so it would be running/jubilant/whatever for an entire bee life tick. I don't think that's a good idea.

**Comment by mezz** [comment]
Bees check for errors on every tick, except the flowers which is every bee work cycle (550 ticks).

**Comment by Vexatos** [comment]
Also, think from a "does it make sense" point of view: Bees going out of their hives to collect things for the queen would have to find their way back to the minecart which may be at a completely different place now, they'd barely be able to follow it and probably die of exhaustion really quickly due to having to fly as fast as they can to catch up.

**Comment by mezz** [comment]
I think this is well within the bounds of Minecraft-logic. 
100s of bees hives can make ~~barrels of honey~~ stacks of quartz from a single flower.

**Comment by Vexatos** [comment]
Yes, but the life of bees itself is actually represented better than one would think.

**Comment by SirSengir** [comment]
Github really needs a "Like"-button. Apiary carts sound good!

**Comment by Vexatos** [comment]
@SirSengir, it's called :+1: or :-1: as a comment ;)

**Comment by buttilda** [comment]
Well most big-game beekeepers nowadays make most of their money by "renting" out their bees to farms that need  abundant pollination to produce (I think one of the most common ones are almonds). They literally shove a bunch of apiaries in a lorry, drive them across the continent, and deposit them on the farm, where they stay during flowering season, a few months later they get loaded back on lorries and driven back home (or a different farm!).

So having them in a minecart wouldn't be that far away from real life ;D I love the idea.

Oh and bees can probably fly much faster than minecraft's minecarts go, so catching up wouldn't be a problem. Finding them would... since bees aren't really "programmed" for living in mobile homes.

**Comment by leagris** [comment]
@SirSengir wrote:

> Github really needs a "Like"-button. Apiary carts sound good!

What king says is ![gold](https://raw.githubusercontent.com/InvictusGraphics/Invictus_Textures/master/assets/minecraft/textures/items/gold_ingot.png)!

**Comment by mezz** [comment]
![2015-11-02_05 22 37](https://cloud.githubusercontent.com/assets/916092/10882711/cfeb1d7a-8121-11e5-9dc3-f195bf93d7b3.png)

It's far from done but I'm making good progress.

**Comment by buttilda** [comment]
+1
Sweet :D

**Comment by mezz** [comment]
![2015-11-02_23 32 09](https://cloud.githubusercontent.com/assets/916092/10903026/0daa8d1a-81ba-11e5-8c7e-6087e1eb5984.png)

Getting there... :)

**Comment by mezz** [comment]
And done! There's a high chance that I broke something gui-networking related since I messed with so much code, I'm still working to test everything. The carts are tested and working well though!
