### ISSUE TITLE
Crash with corrupted forestry leaves with MFR harvester

### ISSUE THREAD

**Issue by NathanMalta** [ForestryMC/ForestryMC#730]
Hello, I recently have created a MFR tree farm using forestry's Blue Mahoe Saplings.  When I turned on the harvester(shear leaves was on), it spit out corrupted leaf blocks and crashed Minecraft.  Minecraft now crashes whenever I attempt to load the world.  Below is a crash report.  Thank you for your time.

https://gist.github.com/mezz/3dc5234580ed02d30761

**Comment by mezz** [comment]
Thanks for the report!
I'll take a look.

**Comment by mezz** [comment]
It looks like MFR isn't grabbing the leaves tile entities. 
When a leaf tries to figure out what type it is, it needs the tile entity and crashes.

Please reply to [this MFR issue](https://github.com/powercrystals/MineFactoryReloaded/issues/329) and link back here.

I just made the leaves named "for.leaves.corrupted" instead of crashing, so you can continue using your world! Grab the [latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/).

**Comment by NathanMalta** [comment]
Ok thank you!

**Comment by Blue-Beaker** [comment]
Just update MFR. Also solves the problem.
