### ISSUE TITLE
Small fonts render poorly, especially with unicode

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#776]
There is a recent mod to fix text and it does a good job: 
http://minecraft.curseforge.com/mc-mods/233069-unicode-font-fixer

The handheld -alyzer text in Forestry is especially bad, and looks blocky.

It should be possible to fix in Forestry. 
@oldjunyi can you tell us what we need to do to fix our font rendering?

**Comment by oldjunyi** [comment]
When Forestry invokes FontRenderer.drawString, my mod will check the GL_MODELVIEW_MATRIX, set the scale ratio from 0.75 to 1.0

More specifically, it does the following work:

``` java
double ratio = GL11.glGetFloat(GL11.GL_MODELVIEW_MATRIX);
GL11.glScaled(1 / ratio, 1 / ratio, 1.0);
GL11.glTranslated(Math.round(text.x * (ratio - 1) * 2) / 2,
        Math.round((text.y + 6) * (ratio - 1) * 2) / 2, 0); // Ensure the x/y offset are multiples of 0.5
```

After checking the source code of Forestry, I found there is a line

``` java
protected float factor = 0.75F;
```

in forestry.core.gui.GuiForestry. Seems it is a factor of font scaling, line spacing and other text formatting. Change it to 1.0 may works.

By the way, it is hard to create small fonts since the Minecraft does not use truetype and it lacks anti-aliasing rendering methods.

**Comment by mezz** [comment]
If I only set the factor to 1.0F, nothing fits on the screen.
I'll play around with it a bit more.
