### ISSUE TITLE
Forestry stable 3.6.6.24 has no recipe for the Escritoire

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#838]
It is not possible to craft an Escritoire in this version of Forestry.

**Comment by mezz** [comment]
The recipe might not show but it still works.
I think it may be a problem with your version of NEI integration. 
This will no longer be an issue with Forestry 4.0 because it has NEI Integration built-in.

![2015-09-22_01 54 41](https://cloud.githubusercontent.com/assets/916092/10014267/fc9ae29e-60cc-11e5-9d2c-bde8883e7d4d.png)

**Comment by mezz** [comment]
@leagris can you confirm that you can craft an escritoire with the recipe above? 
If you can't, we should investigate mod interactions.

**Comment by leagris** [comment]
Thank you. Idk why NEI does not show recipe.

**Comment by leagris** [comment]
Just test now, this is ok. Recipe works in carpenter, so it is an NEI integration issue.

**Comment by mezz** [comment]
Ok thanks for checking!
