### ISSUE TITLE
"Sound Spam" Worktable with GT tools

### ISSUE THREAD

**Issue by JasonMcRay** [ForestryMC/ForestryMC#842]
Ok... I have update to v3.6.7 to test the fixed #750 

It indeed is fixed, but I have discovered other issue :(
When I layout a recipe for example to make Iron Plate
x, H, x
x, I, x
x, I, x

H = Any GT Hammer
I = Iron Ingot
x = nothing

And I put the Hammer and Iron Ingots into the storage area, I start to hear massive ear-busting hammering sound looping again, again, and again until I close the worktable

I remember this issue to be present in the past, then it got somehow fixed, and now it is back.

**Comment by mezz** [comment]
That sounds horrible, excuse the pun. I'll take a look.

**Comment by mezz** [comment]
Looking at decompiled GT, it makes a noise every time you call `GT_MetaGenerated_Tool.getContainerItem`
This is pretty unexpected. I'll see what I can do.

**Comment by mezz** [comment]
I am calling `GT_Generic_Item.hasContainerItem` which really should not make a noise.
However, it is implemented like this:

``` java
    public final boolean hasContainerItem(ItemStack aStack) {
        return this.getContainerItem(aStack) != null;
    }
```

So any time you check, `getContainerItem` makes a sound. I don't think I can work around this. I'm going to say this is a bug with GT, because I need to check for the container item to check the recipe. 

The bug is that `GT_Generic_Item` and `GT_MetaGenerated_Tool` should only make a noise when you do `getContainerItem`, not `hasContainerItem`. This can be accomplished by having `GT_MetaGenerated_Tool` override and implement `hasContainerItem`.

@JasonMcRay Can you report it? I'm not sure where the correct place is. 
This is with gregtech_1.7.10-5.09.02

**Comment by JasonMcRay** [comment]
Done :)

**Comment by mezz** [comment]
Thanks!
