### ISSUE TITLE
Breed trees with more branches

### ISSUE THREAD

**Issue by m2lk** [ForestryMC/ForestryMC#853]
Have you ever though about adding a gene to trees, that allows them to become as large as the ExtraBiomesXL Legend Oak, or at least allow for branching of any size of trees?  Though the legend oaks would have to have their own type of leaves and the legend oak saplings super rare... Alternatively, the branching gene could come as a rare from the regular oak tree (because they rarely branch naturally).

**Comment by mezz** [comment]
I think it would be interesting to have a "branchiness" gene for the trees like height. 
Maybe instead of a new gene, the height factor would be used to make branched trees have more or fewer branches. It would definitely make the worldgen possibilities more interesting.

It would be a lot of work to implement different branch amounts for every tree though.
I'll leave this open since it's a nice idea, but I don't expect it to happen soon.

**Comment by leagris** [comment]
> I think it would be interesting to have a "branchiness" gene for the
> trees like height.
> Maybe instead of a new gene, the height factor would be used to make
> branched trees have more or fewer branches. It would definitely make the
> worldgen possibilities more interesting.
> 
> It would be a lot of work to implement different branch amounts for
> every tree though.
> I'll leave this open since it's a nice idea, but I don't expect it to
> happen soon.

It has been long since I witness some world-generated trees as an option
in Forestry.

I'd leave branching as an internal function of height gene though.
Leave this detail hidden/private in the tree shape generator, while
keeping current genome and API unchanged for compatibility.

#### World generated trees requirements:
1. Any tree specie can be generated in-world. (see 4.)
2. Generated tree genes shall have very basic traits, minimalistic
   sappiness, maturation, girth, height (as do any wild specie in real-World)
3. Biome climate specific layout and chance.
4. Maybe add some wild/cultivated variants of tree species using the
   already existing owner NBT tag. (wild species would have no owner) or
   add a generation cycle gene as it already exist for bees.
5. Possibly: add random gene mutation chance on sapling drop, as a
   difficulty profile option.
