### ISSUE TITLE
Multifarm coundn't accept humus directly

### ISSUE THREAD

**Issue by sfchipan** [ForestryMC/ForestryMC#855]
Maybe this feature had been deleted? If multifarm can accept humus as input material, then I can use compost to craft humus when the fertilizer is lack :)

**Comment by sfchipan** [comment]
version 4.0.0.715

**Comment by 3TUSK** [comment]
In Minecraft 1.5.2 it can't either. (Forestry version unsure) (1.4.7 doesn't have multifarm thing)
Could it be a new feature in configuration, it would be awesome.

**Comment by mezz** [comment]
I'm on the fence about this. The farm design is consistent about it needing apatite.

**Comment by SandGrainOne** [comment]
The Arboretum mode is the farm that, by far, use the most Fertilizer. A small tree farm use a lot more than a big wheat farm. Equalizing this a little bit could be a good thing.

I think the Arboretum farm should take Humus **instead** of dirt. In the same way as the Peat farm takes Bog Earth and not dirt. Humus will still require fertilizer in mod packs without alternative recipes. It could also more easily be changed to include a third component.

This could also be taken further to other farms like the wheat farm. Have a degrading mechanism for the soil so that the input for soil must be maintained and not a one time only thing when you build the farm.

The Arboretum and the Peat farming modes are by far the most interesting ones because they involve more than just water and fertilizer.

**Comment by Vexatos** [comment]
@mezz You could make it accept either. Adding humus would make it use less fertilizer (about as much as a peat bog, I'd guess), but never make it use no fertilizer at all.

**Comment by SandGrainOne** [comment]
Isn't the amount of Fertilizer it uses on making Humus negligible compared to the other operations like placing saplings and cutting down the logs? I have not looked at the code, but I always thought the Fertilizer use was significantly higher than only making Humus would involve.

**Comment by Vexatos** [comment]
@SandGrainOne Good question. I always thought it automatically creating humus from dirt would use the most fertilizer.

**Comment by sfchipan** [comment]
@mezz OK, I‘ve understanded your design. It's doesn't matter actually because fertilizer never been used up... So what's the purpose of the humus crafting by compost?

**Comment by Nirek-K** [comment]
You can use it as hydrated ground to plant things on, without having to deal with the water holes.

**Comment by sfchipan** [comment]
@Nirek-K Oh, I see.
