### ISSUE TITLE
Liquid Milk conflict with MFR

### ISSUE THREAD

**Issue by Bloodmorphed** [ForestryMC/ForestryMC#862]
logs: 
http://files.deathfever.dx.am/client.txt
http://files.deathfever.dx.am/server.txt

Forestry is throwing up this error with these Mods enabled:
Thermal Mods
Forestry
Minefactory Reloaded
Tinkers'

That is the only way I can produce this error. However removing Tinkers' OR MFR removes that error.

Error: Missing List: Forestry:fluids:milk

EDIT:
Oops I might want to include that it only does it when trying to connect to my server. Both client and server have same forge versions, mod versions and exact same configs.

**Comment by mezz** [comment]
Thanks for the report!
Looks like a conflict with Minefactory Reloaded. Both mods add liquid milk blocks.
I'm not sure what the best way to resolve this is. I'll ask around.

**Comment by Bloodmorphed** [comment]
Well my main curiosity is that there are a lot of modpacks that use these mods together without any problems. I'm stumped as to why I am getting it lol. (I am building my own modpack)

**Comment by mezz** [comment]
Oh, of course. You can disable the liquid block in one or both of the mods. That's probably what the mod packs do, they're used to this kind of thing.
Try disabling milk fluid blocks in `config/forestry/fluids.conf`

**Comment by Bloodmorphed** [comment]
That seems to have done it, but I am still curious if I take Tinkers' Construct out the problem disappears. That is so weird as Tinkers' has nothing to do with milk blocks, lol.

**Comment by mezz** [comment]
Tinker's comes into play for a strange reason.
As I understand it, this crash is caused by the client and server disagreeing about which mod "owns" liquid milk. If the mods are not loaded in the same order on the client and server, they will disagree and crash. Somehow having Tinker's in your pack was enough to change the mod load order. 
Thankfully for a mod pack creator, there aren't a lot of things like that.

Anyway glad it's working. Please report any new bugs you find.
