### ISSUE TITLE
Forestry 4.0 is incompatible with BiblioWoods Forestry Edition

### ISSUE THREAD

**Issue by DanNetwalker** [ForestryMC/ForestryMC#869]
I get this crash after updating Forestry to 4.0: http://pastebin.com/8t09d8y9

After consulting with @Wayoftime, Blood Magic creator, he thinks it's Forestry's fault. Could you please take a look at it?

**Comment by WayofTime** [comment]
From what I understand, I think the issue is that Forestry is registering a recipe that has a null output (or a null Item in the ItemStack). The Compression Handler that I have checks the outputs of the recipes and tries to see if they have a compressible form (like redstone blocks). That's what I think is the issue, at any rate.

(Thought I posted before, but I guess I didn't hit the Comment button)

**Comment by mezz** [comment]
Thanks for the report!
I had a similar issue with GregTech, which is extremely strict about recipes.
I'll add Blood Magic to my dev environment and step through to see what's happening.

**Comment by mezz** [comment]
@DanNetwalker my world loaded up fine. Do you have any steps to reproduce, or does it happen when the game loads?

**Comment by DanNetwalker** [comment]
On the lasts steps of game load, not even reaching the main menu. I faced the problem while updating my modpack to the newest versions available. Should I send you a link to a compressed profile that fails exactly that way?

**Comment by mezz** [comment]
Hmm ok. If you can narrow down the mod list as much as possible I can test and fix it more easily. I suspect there is a third mod that is part of this issue.

**Comment by WayofTime** [comment]
From another crash report on the BM github, someone mentioned that it happened when Forestry 4 and Reika's mods (I think RotaryCraft) were installed. Might be a 3-way crash.

**Comment by DanNetwalker** [comment]
(...It may take me a day or two, I'm currently moving from this house to a new one and this is an absolute chaos...)

**Comment by mezz** [comment]
[Forestry 4 and Reika's mods are not compatible yet](https://github.com/ForestryMC/ForestryMC/issues/849). 
It looks like Reika's mods are not included in the original crash report though, so it must be something else.

**Comment by Parker8283** [comment]
I was able to replicate this without Reika's Mods. http://pastebin.com/GQkAVCEn

**Comment by BobHassok** [comment]
I also don't have any of Reika's mods installed; and, Forestry 4.0.8 is crashing with: Binnie's Mod, Biomes O' Plenty, and Blood Magic. Updating BoP fixed its crash, and I disabled Binnie's mod. http://hastebin.com/zitiyireco.coffee

**Comment by Parker8283** [comment]
I've figured it out. It's Forestry, Blood Magic, and BiblioWoods Forestry Edition. http://pastebin.com/hs2UW0i6

This is because BiblioWoods Forestry Edition hasn't been updated to Forestry 4.0, and is therefore creating bad itemstacks.

EDIT: Blood Magic has nothing to do with it. It's just the one catching the bad itemstacks.

**Comment by mezz** [comment]
From [the BiblioWoods addons page](http://www.bibliocraftmod.com/bibliowoods-addons/): 

> These will no longer be updated. They will still work with the listed versions, but since the Furniture Paneler basically can accomplish the same end goal, I see no need to continue updating these. 

Unfortunately the Paneler doesn't seem to work with Forestry 4's TileEntity woods.

I think the solution for now is to remove the BibioWoods Forestry Edition addon and hope they can update.
