### ISSUE TITLE
Java Problem

### ISSUE THREAD

**Issue by StarfireSky** [ForestryMC/ForestryMC#889]
I download the Forestry mod version 4.0.9.38 and it is causing java to crash and I did not get a crash report.

**Comment by mezz** [comment]
Thanks for the report!
Forestry 4 has dropped Java 6 support because [less than 0.05% of modded Minecraft players are using it.](https://github.com/ForestryMC/ForestryMC/issues/881)
Make sure you have the latest version of Java 8, you can download it here: https://java.com/en/download/

If you have Java 6, you should uninstall it. Please let me know if updating Java fixes your issue.
