### ISSUE TITLE
Forestry Workbench destroys TFC Tools in Crafts.

### ISSUE THREAD

**Issue by Bunsan** [ForestryMC/ForestryMC#892]
We are using TFC Beta 0.79.24.816, Forestry 4.1.0.0 in a Forge 10.13.4.1448 environment.

So in TFC you craft a stone brick with a rock (terrafirmacraft:item.LooseRock or search rock in NEI) and a TFC chisel. This can be done in personal crafting guy and does durability damage to the chisel. When done in the Forestry Workbench it destroys the chisel on the first craft. In the crafting window it overlays the chisel with the durability bar change due to craft, easiest to see by using a new chisel, and puts a 2 in the lower left corner.

I've tested further and found the vanilla workbench and the betterstorage crafting station do not do this. This also occurs with recipes I create with minetweaker. Even if the tool does not take durability damage and is given the .reuse() tag it is destroyed. TFC buckets act as expected and give an empty bucket back. I created a minetweaker script with the railcraft crowbar and got the same result. I also tested with a vanilla axe and got the same result with both a .transformDamage() and .reuse() tag. Interestingly the forge multiblock saw works as expected.

**Comment by mezz** [comment]
Thanks for the report!
I'm taking a look at their code, it seems like the chisel doesn't have a container item. I'm missing something, but I'm not sure what yet.

Edit: ah they have custom crafting handlers instead of doing it the normal way. I'll see what I can do to support it.

Edit2: they do it in a very nonstandard way: instead of having a container item with 1 damage applied, they have a crafting event handler that damages the item and sets its stack size to 2 so that when the crafting table consumes one there's one left.

**Comment by mezz** [comment]
Fixed and tested with chisels, in the latest unstable build. 
I'm not going to put this into stable builds until it can get some more real-use testing with TFC tools. Please let me know how it goes.
