### ISSUE TITLE
[Forestry 4 API] Implement backward compatibility

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#905]
Please if possible, I think it would be a good idea to implement Backward compatibility into Forestry 4 API.
- Mark any call to APIv3.6 classes, methods, parameters as deprecated
- On debug option, log deprecated calls to inform mods authors to update.

Please also, implement an in-world data upgrader so Multiblocks, woods and stuffs won't be lost on upgrade

**Comment by Vexatos** [comment]
Long story short: The version is 4 now for a reason. Major version bumps are only made when there are a lot of breaking changes which had to be done. If it wasn't breaking, it would not be called "Forestry 4". If an addon doesn't update to Forestry 4, it's their fault.

**Comment by mezz** [comment]
Unfortunately this is not going to be possible. 
[The only mods that are still known to be incompatible are here](https://github.com/ForestryMC/ForestryMC/labels/Incompatibility).
Right now it's just Reika's (planned to be fixed) and Binnie's mods. Highlands is also incompatible but it looks like it is not being maintained at all.

Forestry's code is a lot more stable with this version, and the API shouldn't get any breaking changes (until the next version of Minecraft).

As for multiblocks and woods, see duplicate issue here: https://github.com/ForestryMC/ForestryMC/issues/795
I spent a long time trying to get wood migration to work but it ended up looking very difficult to support and test, and the solution would only work on random block updates instead of instantly migrating the whole world.
The multiblock logic has completely changed and there is no good way to make sense of the old logic using the new code without a ton of hacks and trial and error testing.
