### ISSUE TITLE
Squeezer not filling liquid containers

### ISSUE THREAD

**Issue by jkenyonc** [ForestryMC/ForestryMC#987]
When I place a bucket, wax capsule, or can in the container slot in the squeezer, it does not fi with honey.

**Comment by jkenyonc** [comment]
Using forestry 4.2 and GregTech 6.00.60.

**Comment by mezz** [comment]
Works fine in the latest Forestry without GregTech. Maybe Greg changes the Fluid ID of honey?

**Comment by mezz** [comment]
@GregoriusT do you know what's happening here?

**Comment by GregoriusT** [comment]
Forestry "recently" changed its fluid Name from "honey" to
"for.honey", since that would be a kindof compatibility breaking
change I adjusted to that and renamed my own Honey Fluid too. But this
is not the Issue.

I would recommend you to NOT hash anything with the Fluid ID, because
Fluid IDs are NOT A FIXED VALUE, Forge itself changes them based on
World/Server, just like Block and Item IDs. If you go via those IDs
then you need to rehash everything on Serverstart/Clientlogin. I know
it is stupid, but I am not in charge of it...

**Comment by mezz** [comment]
Thanks @GregoriusT, that's most likely it.
I replaced any use of fluid ID with fluid name, although this issue was probably just from the table in `ItemRegistryFluids`.

@jkenyonc please try [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/) and let me know if it solves the issue.
